<?php 
/********************************************************
	lang/<lang>/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="用户名：";
$loginStrings[1]="密　码：";
$loginStrings[2]="服务器：";
$loginStrings[3]="类　型：";
$loginStrings[4]="根目录：";
$loginStrings[5]="语　言：";
$loginStrings[6]="进　入";

$loginErrors[0]="受限制的主机地址";
$loginErrors[1]="错误: \"uploads\" 目录丢失";
$loginErrors[2]="错误: \"users\" 目录丢失";
$loginErrors[3]="错误: \"sessions\" 目录丢失";

?>