<?php
include("../lang/eng/pref_identities.inc"); // <-- do not delete
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$piStrings["identities"] = "个人档案设置";
$piStrings["edit"] = "编辑";
$piStrings["name"] = "显示姓名";
$piStrings["email"] = "Email";
$piStrings["replyto"] = "回复地址";
$piStrings["sig"] = "签名档";
$piStrings["add"] = "新建";
$piStrings["new"] = "新建个人档案";
$piStrings["edit_ident"] = "编辑个人档案";
$piStrings["delete"] = "删除";

$piError[1] = "您必须输入“显示姓名”或 Email。";

?>
