<?php
/********************************************************
	lang/gb/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	(C)2003 Lovell Fuller <iloha@lovell.info>
	(C)2005 Andrew Alderwick <andrew@alderwick.co.uk>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/dates.inc");

$lang_datetime["thisyear"] = "%d/%m";		//e.g. "31/12"
$lang_datetime["prevyears"] = "%d/%m/%y"; 	//e.g. "31/12/2002"
$lang_datetime["monthyear"] = "%m %y";		//e.g. "December 2002"
$lang_datetime["verbal"] = '%d %m, %y';  	//e.g. "31st Dec, 2002"
$lang_datetime["verbal_short"] = '%d %m';  	//e.g. "31st Dec"
?>