<?php 
/********************************************************
	lang/gb/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	(C)2005 Andrew Alderwick <andrew@alderwick.co.uk>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginErrors[0]="Unauthorised host";

?>