<?php
/********************************************************
	lang/gb/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	(C)2003 Lovell Fuller <iloha@lovell.info>
	(C)2005 Andrew Alderwick <andrew@alderwick.co.uk>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/main.inc");

$mainStrings[11] = "Empty Rubbish";

$mainErrors[2] = "Couldn't move messages to Rubbish.";
$mainErrors[5] = "Rubbish folder not specified.";
$mainErrors[6] = "Couldn't empty Rubbish";
$mainErrors[8] = "Click on the arrows underneath the column headings to move them.<br>When you've finished, simply close the window.";



?>