<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Torben Rybner, Ziberex (try@ziberex.dk)
	          and Niels Baggesen <nba@users.sourceforge.net>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Ny aftale";
$calStr["edit_schedule"] = "Ret aftale";
$calStr["weekof"] = "Uge: %d";
$calStr["title"] = "Titel:";
$calStr["color"] = "Farve:";

$calStr["color_names"]['Dark Red'] = 'M&oslash;rker&oslash;d';
$calStr["color_names"]['Red'] = 'R&oslash;d';
$calStr["color_names"]['Deep Blue'] = 'M&oslash;rkebl&aring;';
$calStr["color_names"]['Blue'] = 'Bl&aring;';
$calStr["color_names"]['Dark Green'] = 'M&oslash;rkegr&oslash;n';
$calStr["color_names"]['Green'] = 'Gr&oslash;n';
$calStr["color_names"]['Purple'] = 'Lilla';
$calStr["color_names"]['Cyan'] = 'Cyan';
$calStr["color_names"]['Orange'] = 'Orange';
$calStr["color_names"]['Yellow'] = 'Gul';
$calStr["color_names"]['Magenta'] = 'Magenta';
$calStr["color_names"]['No Color'] = 'Ingen farve';

$calStr["starts"] = "Starter:";
$calStr["ends"] = "Slutter:";
$calStr["from"] = "fra:";
$calStr["until"] = "til:";
$calStr["repeat_on"] = "Gentag";
$calStr["of"] = "hver";
$calStr["weeks"] = array(1=>"f&oslash;rste uge", 2=>"anden uge", 3=>"tredje uge", 4=>"fjerde uge"); 
$calStr["weeks"][1] = "f&oslash;rste uge";
$calStr["weeks"][2] = "anden uge";
$calStr["weeks"][3] = "tredie uge";
$calStr["weeks"][4] = "fjerde uge";
$calStr["week_blurb"] = "... i hver m&aring;ned (indtil slutdatoen).<br>Vil blive gentaget hver uge, hvis ingen er valgt.";
$calStr["monthly"] = "Gentag hver m&aring;ned";
$calStr["yearly"] = "Gentag hvert &aring;r";
$calStr["place"] = "Sted:";
$calStr["description"] = "Beskrivelse:";
$calStr["add"] = "Tilf&oslash;j";
$calStr["update"] = "Ret";
$calStr["Delete"] = "Slet";
$calStr["go"] = "V&aelig;lg";
$calStr["disabled"] = "Kalenderen er ikke tilg&aelig;ngelig.";
$calStr["public"] = "F&aelig;lles aftale";
$calStr["publish"] = "Offentligg&oslash;r aftalen";
$calStr['name'] = '%name\'s kalender';
$calStr['public url'] = 'Offentlig URL: %url';
$calStr['no schedules'] = '<p>Der er ingen aftaler i denne uge  <br>Klik p&aring; en dato ovenfor for et oprette en aftale.';
$calStr['no schedules public'] = '<p>Der er ingen offentlige aftaler i denne uge.';
$calStr['all day'] = 'Hele dagen';
$calStr['is all day'] = 'Hele dagen';
$calStr['format'] = 'Format:';
$calStr['boxed'] = 'Kasser';
$calStr['list'] = 'Liste';
$calStr['scale'] = 'Skalering:';
$calStr['bigger'] = 'St&oslash;rre';
$calStr['smaller'] = 'mindre';

?>
