<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
        lang/dk/contacts.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated by Torben Rybner, Ziberex (try@ziberex.dk)
	          and Niels Baggesen <nba@users.sourceforge.net>

********************************************************/

$cStrings[0] = "Kontaktpersoner";
$cStrings[1] = "Tilf&oslash;j kontaktperson";
$cStrings[2] = " kontaktperson";
$cStrings[3] = "Navn";
$cStrings[4] = "E-post";
$cStrings[5] = "URL";
$cStrings[6] = "Gruppe";
$cStrings[7] = "Kommentar";
$cStrings[8] = "Tilf&oslash;j/rediger kontaktperson";
$cStrings[9] = "E-post";
$cStrings[10] = "Ny meddelelse";

$cStrings["close"] = "Luk vinduet";
$cStrings["addto"] = "Tilf&oslash;j kontaktperson til %s";
$cStrings["showgrp"] = "Vis %s";
$cStrings["all"] = "Alle";
$cStrings["instructions"] = "Klik p&aring; navnet for at tilf&oslash;je.  Du kan ogs&aring; klikke p&aring; gruppenavne for at tilf&oslash;je hele gruppen";
$cStrings["share"] = "F&aelig;lles indgang";
$cStrings["add_contact"] = "Tilf&oslash;j kontakt";
$cStrings["edit_contact"] = "Ret kontakt";
$cStrings["add"] = "Tilf&oslash;j";
$cStrings["edit"] = "Ret";
$cStrings["export"] = "Eksporter";
$cStrings["import"] = "Importer";
$cStrings["exportall"] = "Eksporter alle indgange";
$cStrings["exportgroups"] = "Eksporter grupper";
$cStrings["exportentries"] = "Eksporter indgange";
$cStrings["format"] = "Format";
$cStrings["filename"] = "Filnavn";

$cErrors[0] = "Listen med kontaktpersoner er tom";
$cErrors[1] = "Dem angivne indgang findes ikke";

?>
