<?php
include("../lang/eng/dates.inc"); // <-- do not delete
/********************************************************
        lang/dk/dates.inc
        (C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated by Torben Rybner, Ziberex (try@ziberex.dk)
	          and Niels Baggesen <nba@users.sourceforge.net>

********************************************************/

$lang_months[1] = "Januar";
$lang_months[2] = "Februar";
$lang_months[3] = "Marts";
$lang_months[4] = "April";
$lang_months[5] = "Maj";
$lang_months[6] = "Juni";
$lang_months[7] = "Juli";
$lang_months[8] = "August";
$lang_months[9] = "September";
$lang_months[10] = "Oktober";
$lang_months[11] = "November";
$lang_months[12] = "December";

$lang_datetime["short_mon"][1] = "Jan";
$lang_datetime["short_mon"][2] = "Feb";
$lang_datetime["short_mon"][3] = "Mar";
$lang_datetime["short_mon"][4] = "Apr";
$lang_datetime["short_mon"][5] = "Maj";
$lang_datetime["short_mon"][6] = "Jun";
$lang_datetime["short_mon"][7] = "Jul";
$lang_datetime["short_mon"][8] = "Aug";
$lang_datetime["short_mon"][9] = "Sep";
$lang_datetime["short_mon"][10] = "Okt";
$lang_datetime["short_mon"][11] = "Nov";
$lang_datetime["short_mon"][12] = "Dec";

$lang_datetime["dsow"][0] = "s&oslash;n";
$lang_datetime["dsow"][1] = "man";
$lang_datetime["dsow"][2] = "tir";
$lang_datetime["dsow"][3] = "ons";
$lang_datetime["dsow"][4] = "tor";
$lang_datetime["dsow"][5] = "fre";
$lang_datetime["dsow"][6] = "l&oslash;r";

$lang_datetime["dsowl"][0] = "S&oslash;ndag";
$lang_datetime["dsowl"][1] = "Mandag";
$lang_datetime["dsowl"][2] = "Tirsdag";
$lang_datetime["dsowl"][3] = "Onsdag";
$lang_datetime["dsowl"][4] = "Torsdag";
$lang_datetime["dsowl"][5] = "Fredag";
$lang_datetime["dsowl"][6] = "L&oslash;rdag";

$lang_datetime["dsow_short"][0] = "S";
$lang_datetime["dsow_short"][1] = "M";
$lang_datetime["dsow_short"][2] = "T";
$lang_datetime["dsow_short"][3] = "O";
$lang_datetime["dsow_short"][4] = "T";
$lang_datetime["dsow_short"][5] = "F";
$lang_datetime["dsow_short"][6] = "L";

$lang_datetime["today"] = "I dag %t";
$lang_datetime["lastweek"] = "%w %t";
$lang_datetime["thisyear"] = "%d/%m";
$lang_datetime["prevyears"] = "%d/%m-%y";
$lang_datetime["monthyear"] = "%m %y";          //e.g. "January 2002"
$lang_datetime["verbal"] = "%d. %m %y";         //e.g. "Jan 1, 1900"
$lang_datetime["verbal_short"] = "%d. %m";       //e.g. "Jan 1"
$lang_datetime["hour_system"] = 24;                     // 12 or 24
$lang_datetime["ampm"]["am"] = "am";
$lang_datetime["ampm"]["pm"] = "pm";
$lang_datetime["time_format"] = "%h:%m%a";      // %h=hour, %m=minutes, %a="am:pm"
$lang_datetime["hour_format"] = "%h%a";

?>
