<?php
include("../lang/eng/edit_folders.inc"); // <-- do not delete
/********************************************************
        lang/dk/edit_folders.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated by Torben Rybner, Ziberex (try@ziberex.dk)
	          and Niels Baggesen <nba@users.sourceforge.net>

********************************************************/

$efStrings[0] = "H&aring;ndtering af foldere";
$efStrings[1] = "Opret ny folder";
$efStrings[2] = "Opret folder: ";
$efStrings[3] = "Opret";
$efStrings[4] = "Slet folder";
$efStrings[5] = "Slet";
$efStrings[6] = "Omd&oslash;b folder";
$efStrings[7] = "Omd&oslash;b";
$efStrings[8] = "Abonnerede foldere";
$efStrings[9] = "Abonner";
$efStrings[10] = "Foldere uden abonnement";
$efStrings[11] = "Abonner ikke";


$errors[0] = "Opret folder: ";
$errors[1] = "Kunne ikke oprette folder: ";
$errors[2] = "Slettet folder: ";
$errors[3] = "Kunne ikke slette folder: ";
$errors[4] = "Omd&oslash;bt folder: ";
$errors[5] = "Kunne ikke omd&oslash;be folder: ";
$errors[6] = "Der er kun muligt at f&aring; adgang til foldere for IMAP konti.";

?>
