<?php
include("../lang/eng/pref_identities.inc"); // <-- do not delete
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

$piStrings["identities"] = "Identiteter";
$piStrings["edit"] = "Rediger";
$piStrings["name"] = "Navn";
$piStrings["email"] = "E-post";
$piStrings["replyto"] = "Svar til";
$piStrings["sig"] = "Signatur";
$piStrings["add"] = "Tilf&oslash;j";
$piStrings["new"] = "Ny identitet";
$piStrings["edit_ident"] = "Ret identitet";
$piStrings["delete"] = "Slet";
$piStrings["setdef"] = "G&oslash;r til standard";
$piStrings["isdef"] = "(Standard)";

$piError[1] = "Navn eller e-opost adresse skal anf&oslash;res";

?>
