<?php
include("../lang/eng/prefs.inc"); // <-- do not delete
/********************************************************
    lang/dk/prefs.inc
    (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

    This file is part of IlohaMail, and released under GPL.
    See COPYING, or http://www.fsf.org/copyleft/gpl.html

    Translated by Torben Rybner, Ziberex (try@ziberex.dk)
              and Niels Baggesen <nba@users.sourceforge.net>

********************************************************/

$prefHeaderStrings[0] = "Pr&aelig;ferencer";
$prefHeaderStrings[1] = "Indstillinger";
$prefHeaderStrings[2] = "Udseende";
$prefHeaderStrings[3] = "Identiteter";
$prefHeaderStrings[4] = "Filtre";
                                            
$prefsStrings["0.0"] = "Identitet";
$prefsStrings["0.1"] = "Navn: ";
$prefsStrings["0.2"] = "E-post: ";
$prefsStrings["0.3"] = "Dette kan &aelig;ndres p&aring; \"%s\" siden";
$prefsStrings["0.4"] = "Ikke angivet";

$prefsStrings["1.0"] = "Internationalt";
$prefsStrings["1.1"] = "Sprog: ";
$prefsStrings["1.2"] = "Tegns&aelig;t: ";
$prefsStrings["1.3"] = "Tidszone: ";
$prefsStrings["1.4"] = "Urindstilling: ";
$prefsStrings["1.5"][12] = "12 timer";
$prefsStrings["1.5"][24] = "24 timer";
$prefsStrings["1.6"] = "Ugestart: ";
$prefsStrings["1.7"][0] = "S&oslash;ndag";
$prefsStrings["1.7"][1] = "Mandag";
$prefsStrings['1.8'] = 'Sommertid';

$prefsStrings["2.0"] = "Indstillinger for oversigter";
$prefsStrings["2.1"] = "Vis op til ";
$prefsStrings["2.2"] = " meddelelser";
$prefsStrings["2.3"] = "Vis st&oslash;rrelse";
$prefsStrings["2.4"] = "Sorter efter: ";
$prefsStrings["2.5"] = "";
$prefsStrings["2.6"] = "Sorteringsr&aelig;kkef&oslash;lge: ";
$prefsStrings["2.7"] = "";
$prefsStrings["2.8"] = "Vis oversigt over foldere";
$prefsStrings["2.9"] = "Bredde af folderliste";
$prefsStrings["2.10"] = "Check for nye meddelelser hver %n sekunder";
$prefsStrings["2.11"] = "Vis v&aelig;rkt&oslash;jslinie i %m";
$prefsStrings["2.12"]["b"] = "bunden";
$prefsStrings["2.12"]["t"] = "toppen";
$prefsStrings["2.12"]["bt"] = "top og bund";
$prefsStrings["2.13"] = "Arranger kolonner: ";
$prefsStrings["2.14"] = "klik her";
$prefsStrings["2.15"] = "Vis filter/hurtig s&oslash;gning v&aelig;rkt&oslash;j";
$prefsStrings["2.16"] = "Saml meddelelser i tr&aring;de";

$prefsStrings["3.0"] = "Gem automatisk indstillinger";
$prefsStrings["3.1"] = "Gem sendte meddelelser.";
$prefsStrings["3.2"] = "Gem sendte meddelelser i folder: ";
$prefsStrings["3.3"] = "";
$prefsStrings["3.4"] = "T&oslash;m automatisk papirkurven";
$prefsStrings["3.5"] = "Flyt slettede elementer til: ";
$prefsStrings["3.6"] = "";
$prefsStrings["3.7"] = "Hovedfolder: ";
$prefsStrings["3.8"] = "Alternativ folder";
$prefsStrings["3.9"] = "Skjul foldere udenfor abonnement";
$prefsStrings["3.10"] = "Vis kvota %m";
$prefsStrings["3.11"][""] = "vises ikke";
$prefsStrings["3.11"]["m"] = "i meddelelseslisten";
$prefsStrings["3.11"]["f"] = "i folderlisten";
$prefsStrings["3.12"] = "Kladdefolder";

$prefsStrings["4.0"] = "Indstillinger for visning af meddelelser";
$prefsStrings["4.1"] = "Vis i ramme";
$prefsStrings["4.2"] = "M&aelig;rk citater med farve";
$prefsStrings["4.3"] = "Aktivering af denne indstilling kan sl&oslash;ve systemet.";
$prefsStrings["4.4"] = "Konverter URL'er til links";
$prefsStrings["4.5"] = "Vis HTML meddelelser";
$prefsStrings["4.6"] = "Vis billeder i teksten";
$prefsStrings["4.7"] = "Vis bladringslinks";
$prefsStrings["4.8"] = "Marker ikke brev ved bladring";
$prefsStrings['4.9'] = 'Efter sletning/flytning, vis %menu';
$prefsStrings['4.10']['main'] = "Mappe";
$prefsStrings['4.10']['next'] = "N&aelig;ste";
$prefsStrings['4.10']['prev'] = "Forrige";

$prefsStrings["5.0"] = "Signatur";
$prefsStrings["5.1"] = "Inds&aelig;t automatisk signatur";
$prefsStrings["5.2"] = "";

$prefsStrings["6.0"] = "Skriv";
$prefsStrings["6.1"] = "Vis kontakter";
$prefsStrings["6.2"] = "Vis CC/BCC felter";
$prefsStrings["6.3"] = "Luk efter afsendelse";
$prefsStrings["6.4"] = "Skriv ny meddelelse i denne ramme";
$prefsStrings["6.5"] = "Textbox St&oslash;rrelse: ";
$prefsStrings['6.6'] = 'BCC til mig selv som standard';

$prefsStrings["7.0.0"] = "Disk &amp; folder indstillinger";
$prefsStrings["7.0.1"] = "Kvota indstillinger";
$prefsStrings["7.1"] = "Vis antal ul&aelig;ste";
$prefsStrings["7.2"] = "Opdater folderoversigt hver %n sekunder";

$prefsStrings['8.0'] = 'Gr&aelig;nseflade';
$prefsStrings["8.1"] = 'Tema';
$prefsStrings["8.2"] = "JavaScript brug";
$prefsStrings["8.3"] = "Lidt";
$prefsStrings["8.4"] = "Meget";
$prefsStrings["8.5"] = "Automatisk";

$pref_col_title = "Arranger kolonner";
$pref_colstr["order"] = "R&aelig;kkef&oslash;lge";
$pref_colstr["field"] = "Felt";
$pref_col_label['c'] = "Checkbox";
$pref_col_label['a'] = "Vedh&aelig;ftelser";
$pref_col_label['m'] = "M&aelig;rke/status";

$sort_fields['DATE'] = 'Dato';
$sort_fields['SUBJECT'] = 'Emne';
$sort_fields['SIZE'] = 'St&oslash;rrelse';
$sort_fields['INTERNALDATE'] = 'Dato modtaget';
$sort_orders["ASC"] = "Stigende";
$sort_orders["DESC"] = "Faldende";

$prefsButtonStrings[0] = "OK";
$prefsButtonStrings[1] = "Anvend";
$prefsButtonStrings[2] = "Fortryd";
$prefsButtonStrings[3] = "Oprindelig ops&aelig;tning";

$prefs_new_user = "Du logger &aring;benbart p&aring; for f&oslash;rste gang ... Velkommen<br>";
$prefs_new_user .= "Tilpas indstillingerne og klik s&aring; p&aring; \"OK\"";
?>
