<?php
/********************************************************
	lang/eng/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Σελιδοδείκτες";
$bmStrings["identities"] = "Ταυτότητες";
$bmStrings["edit"] = "Εκσυγχρονισμός";
$bmStrings["name"] = "Όνομα";
$bmStrings["url"] = "URL";
$bmStrings["rss"] = "RSS/RDF";
$bmStrings["category"] = "Κατηγορία";
$bmStrings["other"] = "Καθορίστε-&gt;";
$bmStrings["comments"] = "Σχόλια";
$bmStrings["add"] = "Προσθήκη";
$bmStrings["new"] = "Νέα καταχώρηση";
$bmStrings["edit_url"] = "Σύνταξ καταχώρησης";
$bmStrings["delete"] = "Διαγραφή";

$bmError[1] = "Χρειάζεται ονομα ή URL.";
$bmError[2] = "Αυτή η λειτουργία έχει απενεργοποιηθεί.";
?>
