<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Προσθήκη Χρονοδιαγράμματος";
$calStr["edit_schedule"] = "Σύνταξη Χρονοδιαγράμματος";
$calStr["weekof"] = "Εβδομάδα της: %d";
$calStr["title"] = "Τίτλος:";
$calStr["color"] = "Χρώμα:";
$calStr["colors"] = array(
	"#990000"=>"σκούρο κόκκινο",
	"#FF0000"=>"κόκκινο",
	"#000099"=>"βαθύ μπλέ",
	"#0000FF"=>"μπλέ", 
	"#006600"=>"σκούρο πράσινο",
	"#00FF00"=>"πράσινο",
	"#9900FF"=>"μωβ",
	"#00FFFF"=>"κυανό",
	"#FF6600"=>"πορτοκαλί",
	"#FFFF00"=>"κίτρινο",
	"#FF00FF"=>"φούξια",
	""=>"Χωρίς χρώμα");
$calStr["starts"] = "Ξεκινάει στις:";
$calStr["ends"] = "Λήγει στις:";
$calStr["from"] = "από:";
$calStr["until"] = "έως:";
$calStr["repeat_on"] = "Επανάληψη την";
$calStr["of"] = "της κάθε";
$calStr["weeks"] = array(1=>"πρώτης εβδομάδας", 2=>"δεύτερης εβδομάδας", 3=>"τρίτης εβδομάδας", 4=>"τέταρτης εβδομάδας"); 
$calStr["week_blurb"] = "...του κάθε μήνα (μέχρι την ημερομηνία λήξης).<br>Θα επαναληφθεί για όλες τις εβδομάδες, αν δεν επιλεχθεί καμμία.";
$calStr["monthly"] = "Επανάληψη μηνιαίως";
$calStr["yearly"] = "Επανάληψη ετησίως";
$calStr["place"] = "Τοποθεσία:";
$calStr["description"] = "Περιγραφή:";
$calStr["add"] = "Προσθήκη";
$calStr["update"] = "Ενημέρωση";
$calStr["Delete"] = "Διαγραφή";
$calStr["go"] = "Εμπρός";
$calStr["disabled"] = "Η λειτουργία.";
$calStr["public"] = "Να γίνει η καταχώρηση δημόσια"; 
?>
