<?php
/********************************************************
	lang/eng/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/contacts.inc");

$cStrings[0] = "Επαφές";
$cStrings[1] = "Προσθήκη επαφής";
$cStrings[2] = " Επαφή";
$cStrings[3] = "Όνομα";
$cStrings[4] = "Ηλεκτρονική διεύθυνση";
$cStrings[5] = "URL";
$cStrings[6] = "Group";
$cStrings[7] = "Σχόλια";
$cStrings[8] = "Προσθήκη/Σύνταξη Επαφής";
$cStrings[9] = "Ηλεκτρονική διεύθυνση";
$cStrings[10] = "Σύνθεση";

$cStrings["close"] = "Κλείσιμο Παραθύρου";
$cStrings["addto"] = "Προσθήκη επαφών στο %s";
$cStrings["showgrp"] = "Εμφάνιση ομάδων %s";
$cStrings["all"] = "Όλες";
$cStrings["instructions"] = "Πατήστε στο όνομα για να προσθέσετε. Μπορείτε, επίσης, να πατήσετε το όνομα της ομάδας για να προσθέσετε όλα τα μέλη της.";
$cStrings["share"] = "Να γίνει η καταχώρηση δημόσια";
$cStrings["add_contact"] = "Προσθήκη επαφής";
$cStrings["edit_contact"] = "Σύνταξη επαφής";
$cStrings["add"] = "Προσθήκη";
$cStrings["edit"] = "Ανανέωση";
$cErrors[0] = "Ο κατάλογος των επαφών είναι κενός";
$cErrors[1] = "Η πρόσβαση στη καθορισμένη επαφή δε μπόρεσε να γίνει";


?>
