<?php
/********************************************************
	lang/eng/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_contact.inc");

$ecStrings[0] = "Σύνταξη";
$ecStrings[1] = "Προσθήκη";
$ecStrings[2] = " Επαφής";
$ecStrings[3] = "Ονοματεπώνυμο";
$ecStrings[4] = "Ηλεκτρονική διεύθυνση";
$ecStrings[5] = "URL";
$ecStrings[6] = "Ομάδα";
$ecStrings[7] = "Σχόλια";
$ecStrings[8] = "Τηλέφωνο Κατοικίας";
$ecStrings[9] = "Τηλέφωνο Εργασίας";
$ecStrings[10] = "Κινητό Τηλέφωνο";
$ecStrings[11] = "Διεύθυνση";
$ecStrings[12] = "Εναλλ. Ηλεκτρονική διεύθυνση";
$ecStrings[13] = "Διαγραφή";
$ecStrings[14] = "¶λλο";
$ecStrings[15] = "Όνομα";
$ecStrings[16] = "Επώνυμο";
$ecStrings[17] = "Οδός";
$ecStrings[18] = "Πόλη";
$ecStrings[19] = "Πολιτεία / Νομός";
$ecStrings[20] = "Ταχυδρομικός Κώδικας";
$ecStrings[21] = "Χώρα";


$errors[0] = "Δεν μπόρεσα να προσθέσω την επαφή: Σφάλμα στη βάση δεδομένων.";
$errors[1] = "Υπάρχει ήδη μια καταχώρηση με τη διεύθυνση αυτή.";
$errors[2] = "Κάντε κλίκ ";
$errors[3] = "εδώ";
$errors[4] = " για να συντάξετε εκείνη την επαφή αντ'αυτής.";
$errors[5] = "Η Επαφή δεν βρέθηκε ή δεν επιτρέπεται η πρόσβαση.";
$errors[6] = "Θέλετε με βεβαιότητα να διαγράψετε τη καταχώρηση στο όνομα \"";
$errors[7] = "\";";

?>
