<?php
/********************************************************
	lang/eng/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_folders.inc");

$efStrings[0] = "Διαχείριση Φακέλων";
$efStrings[1] = "Δημιουργία νέου φακέλου";
$efStrings[2] = "Δημιουργία φακέλου: ";
$efStrings[3] = "Δημιουργία";
$efStrings[4] = "Διαγραφή φακέλου";
$efStrings[5] = "Διαγραφή";
$efStrings[6] = "Μετονομασία φακέλου";
$efStrings[7] = "Μετονομασία";
$efStrings[8] = "Εγγεγραμμενοι φάκελοι";
$efStrings[9] = "Εγγραφή";
$efStrings[10] = "Απεγγεγραμμένοι φάκελοι";
$efStrings[11] = "Απεγγραφή";


$errors[0] = "Δημιουργία φακέλου: ";
$errors[1] = "Αδυναμία δημιουργίας φακέλου: ";
$errors[2] = "Διαγραφή φακέλου: ";
$errors[3] = "Αδυναμία διαγραφής φακέλου: ";
$errors[4] = "Μετονομασία φακέλου: ";
$errors[5] = "Αδυναμία μετονομασίας φακέλου: ";
$errors[6] = "Η υποστήριξη φακέλων είναι διαθέσιμη μόνο για λογαριασμούς τύπου IMAP.";

?>
