<?php
/********************************************************
	lang/eng/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/main.inc");

$mainMessages["delete"] = "Διαγραφή %n επιστολής/ών";
$mainMessages["move"] = "Μετακίνηση %n επιστολής/ών στο %f";

$mainStrings[0] = "Εμφανίζονται %p από %n";
$mainStrings[1] = " επιστολές βρέθηκαν";
$mainStrings[2] = "Προηγούμενο";
$mainStrings[3] = "";
$mainStrings[4] = "Επόμενο";
$mainStrings[5] = "";
$mainStrings[6] = "Θέμα";
$mainStrings[7] = "Προς";
$mainStrings[8] = "Από";
$mainStrings[9] = "Ημερομηνία";
$mainStrings[10] = "Διαγραφή";
$mainStrings[11] = "¶δειασμα απορριμμάτων";
$mainStrings[12] = "Μετακίνηση";
$mainStrings[13] = "Αναζήτηση";
$mainStrings[14] = "Μέγεθος";
$mainStrings[15] = "άνευ τίτλου";
$mainStrings[16] = "Εμφάνιση";
$mainStrings[17] = "Έλεγχως νέων";
$mainStrings[18] = "Διαγραφή όλων";
$mainStrings[19] = "Ακύρωση";
$mainStrings[20] = "Σήμανση ως %b";
$mainStrings[21] = "Διαβασμένο";
$mainStrings[22] = "Αδιάβαστο";
$mainStrings[23] = "Επιλογή...";
$mainStrings[24] = "Εφαρμογή φίλτρου";
$mainStrings[25] = "Σήμανση";
$mainStrings[26] = "Σηματνικό";
$mainStrings[27] = "Φίλτρα:";
$mainStrings[28] = "Όλα τα φίλτρα";
$mainStrings[29] = "Εφαρμογή";
$mainStrings[30] = "Γρήγορη αναζήτηση:";
$mainStrings[31] = "Επιλογή";


$mainErrors[0] = "Δεν βρέθηκαν επιστολές σε αυτό τον φάκελο";
$mainErrors[1] = "Δεν υπάρχουν επιστολές σε αυτό τον φάκελο";
$mainErrors[2] = "Αδυναμία μετακίνησης επιστολών στα απορρίμματα.";
$mainErrors[3] = "Αδυναμία σήμανσης των επιστολών ως διεγραμμένες.";
$mainErrors[4] = "Αδυναμία μετακίνησης των επιστολών.";
$mainErrors[5] = "Δεν έχει οριστεί φάκελος απορριμμάτων.";
$mainErrors[6] = "Αδυναμία αδειάσματος των απορριμμάτων.";
$mainErrors[7] = "Είστε σίγουρος πως θέλετε να διαγράψετε ΟΛΕΣ τις επιστολές στο %f?";
$mainErrors[8] = "Πατήστε τα βελάκια κάτω από τις επικεφαλίδες των στηλών για να τις μετακινήσετε.<br>Όταν τελειώσετε, απλά κλείστε το παράθυρο."; 

?>
