<?php
/********************************************************
	lang/eng/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_colors.inc");

$pcStrings["0"] = "Εισάγετε έναν κωδικό χρώματος HTML για το κάθε μέρος.";
$pcStrings["0.1"] = "Χρησιμοποιήστε το ";
$pcStrings["0.2"] = "Χρωματολόγιο";
$pcStrings["0.3"] = " για να βρείτε τους κατάλληλους χρωματικούς κώδικες.";
$pcStrings["0.4"] = "Ρυθμίσεις που το θεματικό παρακάμπτει, δε μπορούν να μεταβληθούν.";
$pcStrings["1.0"] = "Γραμμή εργαλείων";
$pcStrings["2.0"] = "Λίστα φακέλων";
$pcStrings["3.0"] = "Κυρίως";
$pcStrings["3.1"] = "Υπόβαθρο Επικεφαλίδας: ";
$pcStrings["3.2"] = "Κείμενο Επικεφαλίδας: ";
$pcStrings["3.3"] = "Σκούρο Υπόβαθρο: ";
$pcStrings["3.4"] = "Φωτεινό κείμενο: ";
$pcStrings["4.0"] = "Διάφορα";
$pcStrings["4.1"] = "Παραπομπές: ";
$pcStrings["5.0"] = "Γραμματοσειρές";
$pcStrings["5.1"] = "Οικογένεια γραμματοσειράς";
$pcStrings["5.2"] = "Μέγεθος γραμματοσειράς: ";
$pcStrings["5.3"] = "Μέγεθος μικρών γραμματοσειρών: ";
$pcStrings["5.4"] = "Μέγεθος γραμματοσειράς μενού: ";
$pcStrings["5.5"] = "Μέγεθος γραμματοσειράς λίστας φακέλων: ";
$pcStrings["5.6"] = "¶λλα: ";

							
$pcPortions = array( "Υπόβαθρο: ", "Συντομεύσεις: ", "Κείμενο: ", "Έντονο: ");

?>
