<?php
/********************************************************
	lang/eng/prefs.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/prefs.inc");

$prefHeaderStrings[0] = "Προτιμήσεις";
$prefHeaderStrings[1] = "Γενικά";
$prefHeaderStrings[3] = "Ταυτότητες";
$prefHeaderStrings[2] = "Εμφάνιση";
$prefHeaderStrings[4] = "Φίλτρα";

											
$prefsStrings["0.0"] = "Εξ'ορισμού Ταυτότητα";
$prefsStrings["0.1"] = "Όνομα: ";
$prefsStrings["0.2"] = "Ηλεκτρονική διεύθυνση: ";
$prefsStrings["0.3"] = "Αλλαγές μπορούν να γίνουν στη σελίδα \"%s\".";
$prefsStrings["0.4"] = "Ακαθόριστα";
$prefsStrings["1.0"] = "Διεθνείς";
$prefsStrings["1.1"] = "Περιβάλλον: ";
$prefsStrings["1.2"] = "Σύνολο χαρακτήρων: ";
$prefsStrings["1.3"] = "Ζώνη ώρας: ";
$prefsStrings["1.4"] = "Εμφάνιση ώρας: ";
$prefsStrings["1.5"] = array(12=>"12ωρο ρολόι", 24=>"24ωρο ρολόι");
$prefsStrings["2.0"] = "Επιλογές εμφάνισης λίστας";
$prefsStrings["2.1"] = "Εμφάνιση μέχρι ";
$prefsStrings["2.2"] = " τεμάχια";
$prefsStrings["2.3"] = "Εμφάνιση μεγέθους";
$prefsStrings["2.4"] = "Ταξινόμηση ως προς: ";
$prefsStrings["2.5"] = "";
$prefsStrings["2.6"] = "Φορά ταξινόμησης: ";
$prefsStrings["2.7"] = "";
$prefsStrings["2.8"] = "Εμφάνιση λίστας φακέλων";
$prefsStrings["2.9"] = "Πλάτος λίστας φακέλων";
$prefsStrings["2.10"] = "Έλεγχος για νέες επιστολές κάθε %n δευτερόλεπτα";
$prefsStrings["2.11"] = "Εμφάνιση γραμμής εργαλείων %m";
$prefsStrings["2.12"] = array("b"=>"κάτω", "t"=>"πάνω", "bt"=>"πάνω και κάτω");
$prefsStrings["2.13"] = "Αναδιοργάνωση στηλών: ";
$prefsStrings["2.14"] = "Πατήστε εδώ";
$prefsStrings["2.15"] = "Εμφάνιση εργαλείων φίλτρου/γρήγορης αναζήτησης";
$prefsStrings['2.16'] = 'Οι συζητήσεις να παρατάσσονται μαζί';
$prefsStrings["3.0"] = "Αυτόματη αποθήκευση επιλογών";
$prefsStrings["3.1"] = "Αποθήκευση απεσταλμένων τεμαχίων.";
$prefsStrings["3.2"] = "Οι απεσταλμένες επιστολές να αποθηκεύονται στο φάκελο: ";
$prefsStrings["3.3"] = "";
$prefsStrings["3.4"] = "Αυτόματη διαγραφή απορριμμάτων";
$prefsStrings["3.5"] = "Μετακίνηση διεγραμμένων τεμαχίων στο φάκελο: ";
$prefsStrings["3.6"] = "";
$prefsStrings["3.7"] = "Ριζικός Κατάλογος: ";
$prefsStrings["3.8"] = "Άλλο";
$prefsStrings["3.9"] = "Απόκρυψη μη εγγεγγραμένων φακέλων";
$prefsStrings["3.10"] = "Εμφάνιση ορίου χώρου %m";
$prefsStrings["3.11"] = array(""=>"Να μην εμφανίζεται", "m"=>"Στη λίστα επιστολών", "f"=>"Στη λίστα φακέλων");
$prefsStrings["4.0"] = "Επιλογές Εμφάνισης Επιστολών";
$prefsStrings["4.1"] = "Εμφάνιση μέσα σε πλαίσιο";
$prefsStrings["4.2"] = "Χρωματισμός παραθεμάτων";
$prefsStrings["4.3"] = "Ενεργοποίηση αυτής της επιλογής μπορεί να καθυστερήσει το σύστημα.";
$prefsStrings["4.4"] = "Μετατροπή URLs σε links";
$prefsStrings["4.5"] = "Εμφάνιση επιστολών HTML";
$prefsStrings["4.6"] = "Εμφάνιση εικόνων εσωτερικά";
$prefsStrings["4.7"] = "Εμφάνιση συντομεύσεων πλοήγησης";
$prefsStrings["4.8"] = "Να μη σημαδεύονται οι επιστολές κατά τη διέλευση";
$prefsStrings['4.9'] = 'Έπειτα από διαγραφή/μετακίνηση, να εμφανίζεται: %menu';
$prefsStrings['4.10']= array('main'=>"Φάκελος",'next'=>'Επόμενη','prev'=>'Προηγούμενη');
$prefsStrings["5.0"] = "Υπογραφή";
$prefsStrings["5.1"] = "Εξ'ορισμού, να εμφανίζεται η υπογραφή";
$prefsStrings["5.2"] = "";
$prefsStrings["6.0"] = "Σύνθεση";
$prefsStrings["6.1"] = "Εμφάνιση επαφών";
$prefsStrings["6.2"] = "Εμφάνιση πεδίων Κοινοποίησης/Κρυφής Κοινοποίησης";
$prefsStrings["6.3"] = "Κλείσιμο μετά την αποστολή";
$prefsStrings["6.4"] = "Σύνθεση μέσα σε πλαίσιο";
$prefsStrings["6.5"] = "Μέγεθος κειμενογράφου: ";
$prefsStrings['6.6'] = "Κρυφή Κοινοποίηση στον εαυτό εξ'ορισμού";
$prefsStrings["7.0.0"] = "Επιλογές Δίσκου &amp; Φακέλων";
$prefsStrings["7.0.1"] = "Επιλογές Ορίων Χώρου";
$prefsStrings["7.1"] = "Εμφάνιση αριθμού αδιάβαστων";
$prefsStrings["7.2"] = "Ανανέωση λίστας φακέλου κάθε %n δευτερόλεπτα";
$prefsStrings['8.0'] = 'Περιβάλλον Χρήστη';
$prefsStrings["8.1"] = 'Θεματικό';
$prefsStrings["8.2"] = "Χρήση JavaScript";
$prefsStrings["8.3"] = "Χαμηλή";
$prefsStrings["8.4"] = "Υψηλή";

$pref_col_title = "Αναταξινόμηση Στηλών";
$pref_colstr["order"] = "Σειρά";
$pref_colstr["field"] = "Πεδίο";
$pref_col_label['c'] = "Κουτί Μαρκαρίσματος";
$pref_col_label['a'] = "Επισυναπτώμενα";
$pref_col_label['m'] = "Σημάνσεις/κατάσταση";

$sort_fields=array('DATE'=>'Ώρα αποστολής', 'SUBJECT'=>'Θέμα', 'SIZE'=>'Μέγεθος');
$sort_fields['INTERNALDATE'] = 'Ώρα παραλαβής';
$sort_orders=array("ASC"=>"Αυξητική", "DESC"=>"Μειωτική");

$prefsButtonStrings = array( 0=> "Update", 1=>"Εφαρμογή", 2=> "Ακύρωση", 3=> "Εξ'ορισμού");

$prefs_new_user = "Φαίνεται πως μπαίνετε για πρώτη φορά... καλωσήρθατε!<br>";
$prefs_new_user .= "Παρακαλώ κάντε τις παρακάτω ρυθμίσεις, έπειτα πατήστε το \"Εφαρμογή\"";
?>
