<?php
/********************************************************
	lang/eng/bookmarks.inc
	(C)2004 Cezary Jackiewicz <cjackiewicz@poczta.onet.pl>
	
	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings['pubtitle'] = '%name - Ulubione';
$bmStrings["bookmarks"] = "Ulubione";
$bmStrings["identities"] = "To¿samo¶ci";
$bmStrings["edit"] = "Zmodyfikuj";
$bmStrings["name"] = "Nazwa";
$bmStrings["url"] = "URL";
$bmStrings["rss"] = "RSS/RDF";
$bmStrings["category"] = "Kategoria";
$bmStrings["other"] = "podaj-&gt;";
$bmStrings["comments"] = "Komentarz";
$bmStrings["add"] = "Dodaj";
$bmStrings["new"] = "Nowa pozycja";
$bmStrings["edit_url"] = "Edycja";
$bmStrings["delete"] = "Usuñ";
$bmStrings['refresh'] = 'Od¶wie¿';
$bmStrings['private'] = 'Pozycja prywatna';
$bmStrings['public url'] = 'URL publiczny: %url';
$bmStrings['pubtitlenews'] = '%name - Kana³y RSS';
$bmStrings['rss feeds'] = 'Kana³y RSS';

$bmError[1] = "Wymagana jest nazwa lub adres";
$bmError[2] = "Ta w³a¶ciwo¶æ zostanie wy³±czona.";
?>
