<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2004 Cezary Jackiewicz <cjackiewicz@poczta.onet.pl>
	
	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Dodaj zdarzenie";
$calStr["edit_schedule"] = "Edytuj zdarzenie";
$calStr["weekof"] = "Tydzieñ: %d";
$calStr["title"] = "Tytu³:";
$calStr["color"] = "Kolor:";
$calStr["colors"] = array("#990000"=>"Ciemnoczerwony", "#FF0000"=>"Czerwony", "#000099"=>"Granatowy", "#0000FF"=>"Niebieski", 
					"#006600"=>"Ciemnozielony", "#00FF00"=>"Zielony", "#9900FF"=>"Fioletowy", "#00FFFF"=>"Niebieskozielony",
					"#FF6600"=>"Pomarañczowy", "#FFFF00"=>"¯ó³ty", "#FF00FF"=>"Purpurowy", ""=>"Brak koloru");
$calStr["starts"] = "Start:";
$calStr["ends"] = "Koniec:";
$calStr["from"] = "od:";
$calStr["until"] = "do:";
$calStr["repeat_on"] = "powtarzalno¶æ";
$calStr["of"] = "ka¿dy";
$calStr["weeks"] = array(1=>"pierwszy tydzieñ", 2=>"drugi tydzieñ", 3=>"trzeci tydzieñ", 4=>"czwarty tydzieñ"); 
$calStr["week_blurb"] = "...ka¿dego miesi±ca (do koñca okre¶lonej daty).<br>Zostanie powtórzone ka¿dego tygodnia je¿eli nic nie zosta³o zaznaczone.";
$calStr["monthly"] = "Powtarzaj co miesi±c";
$calStr["yearly"] = "Powtarzaj co rok";
$calStr["place"] = "Miejsce:";
$calStr["description"] = "Opis:";
$calStr["add"] = "Dodaj";
$calStr["update"] = "Zmodyfikuj";
$calStr["Delete"] = "Usuñ";
$calStr["go"] = "Id¼";
$calStr["disabled"] = "W³a¶ciwo¶æ kalendarza zosta³a wy³±czona.";
$calStr["public"] = "Udostêpnij pozycjê"; 
$calStr["publish"] = "Wpis dostêpny dla wszystkich";
$calStr['name'] = ' %name - terminarz';
$calStr['public url'] = 'Publiczny URL: %url';
$calStr['no schedules'] = '<p>Nic nie zosta³o zaplanowane na ten tydzieñ.  <br>Kliknij na datê poni¿ej aby wprowadziæ nowe zadanie.';
$calStr['no schedules public'] = '<p>Nic nie zosta³o zaplanowane na ten tydzieñ.';
$calStr['all day'] = "Ca³y dzieñ";
$calStr['is all day'] = 'To jest ca³odniowe zdarzenie';

$calStr["color_names"]['Dark Red'] = 'Ciemnoczerwony';
$calStr["color_names"]['Red'] = 'Czerwony';
$calStr["color_names"]['Deep Blue'] = 'Granatowy';
$calStr["color_names"]['Blue'] = 'Niebieski';
$calStr["color_names"]['Dark Green'] = 'Ciemnoszary';
$calStr["color_names"]['Green'] = 'Zielony';
$calStr["color_names"]['Purple'] = 'Fioletowy';
$calStr["color_names"]['Cyan'] = 'Niebieskozielony';
$calStr["color_names"]['Orange'] = 'Pomarañczowy';
$calStr["color_names"]['Yellow'] = '¯ó³ty';
$calStr["color_names"]['Magenta'] = 'Purpurowy';
$calStr["color_names"]['No Color'] = 'Brak koloru';
$calStr['format'] = 'Format:';
$calStr['boxed'] = 'Ikony';
$calStr['list'] = 'Lista';
$calStr['scale'] = 'Skala:';
$calStr['bigger'] = 'Wiêkszy';
$calStr['smaller'] = 'Mniejszy';
?>
