<?php
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
	lang/pl/compose.inc
	(C) 2002 Marcin Piliszczuk <marti@net26.pl>
	(C)2004 Cezary Jackiewicz <cjackiewicz@poczta.onet.pl>
	
	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings[0] = "Temat";
$composeHStrings[1] = "Od";
$composeHStrings[2] = "Do";
$composeHStrings[3] = "DW";
$composeHStrings[4] = "UDW";
$composeHStrings[5] = "Data";

$composeStrings[0] = "Nowa wiadomo¶æ";
$composeStrings[1] = "Wy¶lij wiadomo¶æ";
$composeStrings[2] = "Za³±cz";
$composeStrings[3] = "Wstaw podpis";
$composeStrings[4] = "Za³±cznik";
$composeStrings[5] = "Poka¿ ksi±¿kê adresow±";
$composeStrings[6] = "Ukryj ksi±¿kê adresow±";
$composeStrings[7] = "Tre¶æ wiadomo¶ci:";
$composeStrings[8] = "Dodaj";
$composeStrings[9] = "%d, %s napisa³(a):\n";
$composeStrings[10] = "--- Tre¶æ orygina³u ---\n";
$composeStrings[11] = "Zamknij okno";
$composeStrings[12] = "Sprawd¼ pisowniê";
$composeStrings[13] = "Popraw pisowniê";
$composeStrings[14] = "Bez zmian";
$composeStrings[15] = "Mo¿liwe b³êdy w pisowni";
$composeStrings[16] = "Zmiany w pisowni";
$composeStrings[17] = "ignoruj";
$composeStrings[18] = "usuñ";
$composeStrings[19] = "Dodaj ten adres do UDW";

$composeStrings["title"] = "Nowa wiadomo¶æ";
$composeStrings['save'] = 'Zapisz';

$composeErrors[0] = "Pole tematu jest puste. Proszê podaæ temat lub nacisn±æ \"".$composeStrings[1]."\" ponownie by wys³aæ wiadomo¶æ.";
$composeErrors[1] = "Pole \"Od\" jest puste.  Proszê wprowadziæ swój adres e-mailowy.";
$composeErrors[2] = "Pole \"Do\" jest puste.  Proszê okre¶liæ adres odbiorcy.";
$composeErrors[3] = "Dodanie za³±cznika nie powiod³o siê.";
$composeErrors[4] = "Nie otrzymano ¿adnych plików.";
$composeErrors[5] = "Z powodu ochrony przed spamem, mo¿esz wys³aæ wiadomo¶æ do %1 osób/osoby (%2 w trakcie ca³ej sesji) co %3 sekund.";
$composeErrors[6] = "Nie znaleziono b³êdów pisowni.";
$composeErrors[7] = "Spawdzanie pisowni nie jest dostêpne dla podanego jêzyka.";
$composeErrors[8] = "(u¿yto s³ownika %s)";
?>	
