<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/pl/contacts.inc
	(C) 2002 Marcin Piliszczuk <marti@net26.pl>
	(C)2004 Cezary Jackiewicz <cjackiewicz@poczta.onet.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings[0] = "Ksi±¿ka adresowa";
$cStrings[1] = "Dodaj osobê";
$cStrings[2] = " Ksi±¿ka adresowa";
$cStrings[3] = "Imiê / Nazwisko";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Grupa";
$cStrings[7] = "Komentarze";
$cStrings[8] = "Dodaj/Edytuj Wpis";
$cStrings[9] = "Email";
$cStrings[10] = "Nowa wiadomo¶æ";

$cStrings["close"] = "Zamknij okno";
$cStrings["addto"] = "Dodaj kontakt do %s";
$cStrings["showgrp"] = "Poka¿ %s";
$cStrings["all"] = "Wszystko";
$cStrings["instructions"] = "Kliknij na nazwê aby dodaæ. Mo¿esz tak¿e klikn±æ na opis grupy ¿eby dodaæ wszystkich z grupy.";
$cStrings["share"] = "Pozycja dostêpna dla wszystkich";
$cStrings["add_contact"] = "Dodaj";
$cStrings["edit_contact"] = "Edycja";
$cStrings["add"] = "Dodaj";
$cStrings["edit"] = "Modyfikuj";

$cStrings["export"] = "Eksport";
$cStrings["import"] = "Import";
$cStrings["exportall"] = "Wyeksportuj wszystkie pozycje";
$cStrings["exportgroups"] = "Wyeksportuj grupy";
$cStrings["exportentries"] = "Wyeksportuj pozycje";
$cStrings["format"] = "Format";
$cStrings["filename"] = "Nazwa pliku";

$cErrors[0] = "Lista kontaktów jest pusta";
$cErrors[1] = "Nie mo¿na uzyskaæ dostêpu do podanego wpisu.";
?>
