<?php
include("../lang/eng/edit_folders.inc"); // <-- do not delete
/********************************************************
	lang/pl/edit_folders.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>
	(C)2004 Cezary Jackiewicz <cjackiewicz@poczta.onet.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings[0] = "Zarz±dzanie folderami";
$efStrings[1] = "Utwórz nowy folder";
$efStrings[2] = "Utwórz folder: ";
$efStrings[3] = "Utwórz";
$efStrings[4] = "Usuñ folder";
$efStrings[5] = "Usuñ";
$efStrings[6] = "Zmieñ nazwê folderu";
$efStrings[7] = "Rename";
$efStrings[8] = "Subskrybuj foldery";
$efStrings[9] = "Subskrybuj";
$efStrings[10] = "Odsubskrybuj foldery";
$efStrings[11] = "Odsubskrybuj";

$errors[0] = "Utwórzono folder: ";
$errors[1] = "Nie mo¿na utworzyæ folderu: ";
$errors[2] = "Usuniêto folder: ";
$errors[3] = "Nie mo¿na usun±æ folderu: ";
$errors[4] = "Zmieniono nazwê folderu: ";
$errors[5] = "Nie mo¿na zmieniæ nazwy folderu: ";
$errors[6] = "Obs³uga folderów jest dostêpna tylko dla protoko³u IMAP.";

?>
