<?php
include("../lang/eng/main.inc"); // <-- do not delete
/********************************************************
	lang/pl/main.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>
	(C)2004 Cezary Jackiewicz <cjackiewicz@poczta.onet.pl>
	
	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$mainMessages["delete"] = "Usuniêtych wiadomo¶ci: %n";
$mainMessages["move"] = "Przeniesionych wiadomo¶ci do %f: %n";

$mainStrings[0] = "Wy¶wietlono %p z %n wiadomo¶ci";
$mainStrings[1] = " wiadomo¶ci";
$mainStrings[2] = "Poprzednia";
$mainStrings[3] = " wiad.";
$mainStrings[4] = "Nastêpna";
$mainStrings[5] = " wiad.";
$mainStrings[6] = "Temat";
$mainStrings[7] = "Do";
$mainStrings[8] = "Od";
$mainStrings[9] = "Data";
$mainStrings[10] = "Usuñ";
$mainStrings[11] = "Opró¿nij kosz";
$mainStrings[12] = "Przenie¶";
$mainStrings[13] = "Szukaj";
$mainStrings[14] = "Rozmiar";
$mainStrings[15] = "bez tytu³u";
$mainStrings[16] = "Poka¿";
$mainStrings[17] = "Pobierz nowe";
$mainStrings[18] = "Usuñ wszystkie";
$mainStrings[19] = "Anuluj";
$mainStrings[20] = "Zaznacz jako %b";
$mainStrings[21] = "przeczytan±";
$mainStrings[22] = "nieprzeczytan±";
$mainStrings[23] = "Wybierz...";
$mainStrings[24] = "Zastosuj filtr";
$mainStrings[25] = "Zaznacz";
$mainStrings[26] = "wa¿n±";
$mainStrings[27] = "Filtry";
$mainStrings[28] = "Wszystkie filtry";
$mainStrings[29] = "Zastosuj";
$mainStrings[30] = "Szybkie wyszukiwanie:";
$mainStrings[31] = "Wybór";
$mainStrings[32] = 'Zwyk³y';


$mainErrors[0] = "Nieznaleziono  wiadomo¶ci w tym folderze";
$mainErrors[1] = "Brak wiadomo¶ci w tym folderze.";
$mainErrors[2] = "Nie mo¿na przenie¶æ wiadomo¶ci do kosza.";
$mainErrors[3] = "Nie mo¿na oznaczyæ wiadomo¶ci jako usuniêtych.";
$mainErrors[4] = "Nie mo¿na przenie¶æ wiadomo¶ci.";
$mainErrors[5] = "Nie okre¶lono folderu dla kosza.";
$mainErrors[6] = "Nie mo¿na opró¿niæ kosza";
$mainErrors[7] = "Czy na pewno chcesz usun±æ WSZYSTKIE wiadomo¶ci w %f?";
$mainErrors[8] = "Kliknij na strza³kê poni¿ej nag³ówka kolumny, ¿eby j± przesun±æ.<br>Po wykonaniu operacji, poprostu zamknij okno.";


?>
