<?php
include("../lang/eng/prefs.inc"); // <-- do not delete
/********************************************************
	lang/pl/prefs.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>
	(C)2004,2005 Cezary Jackiewicz <cjackiewicz@poczta.onet.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$prefHeaderStrings[0] = "Ustawienia";
$prefHeaderStrings[1] = "Ogólne";
$prefHeaderStrings[2] = "Wygl±d";
$prefHeaderStrings[3] = "To¿samo¶ci";
$prefHeaderStrings[4] = "Filtry";

											
$prefsStrings["0.0"] = "To¿samo¶æ domy¶lna";
$prefsStrings["0.1"] = "Imiê: ";
$prefsStrings["0.2"] = "Email: ";
$prefsStrings["0.3"] = "Zmiany moga byæ wykonane na stronie \"%s\".";
$prefsStrings["0.4"] = "niepodano";
$prefsStrings["1.0"] = "Miedzynarodowe";
$prefsStrings["1.1"] = "Jêzyk interfejsu: ";
$prefsStrings["1.2"] = "Zestaw znaków: ";
$prefsStrings["1.3"] = "Strefa czasowa: ";
$prefsStrings["1.4"] = "Opcje czasu: ";
$prefsStrings["1.5"] = array(12=>"12-godzinny zegar", 24=>"24-godzinny zegar");
$prefsStrings["1.6"] = "Tydzieñ zaczyna siê od: ";
$prefsStrings["1.7"] = array(0=>"Niedzieli", 1=>"Poniedzia³ku");
$prefsStrings["2.0"] = "Opcje wy¶wietlania listy";
$prefsStrings["2.1"] = "Pokazuj do ";
$prefsStrings["2.2"] = " wiadomo¶ci";
$prefsStrings["2.3"] = "Poka¿ rozmiar";
$prefsStrings["2.4"] = "Sortuj wed³ug: ";
$prefsStrings["2.5"] = "";
$prefsStrings["2.6"] = "Porz±dek sortowania: ";
$prefsStrings["2.7"] = "";
$prefsStrings["2.8"] = "Poka¿ listê folderów";
$prefsStrings["2.9"] = "Szeroko¶æ listy folderów";
$prefsStrings["2.10"] = "Sprawdzaj nowe wiadomo¶ci co %n sekund";
$prefsStrings["2.11"] = "Poka¿ pasek narzêdzi na %m";
$prefsStrings["2.12"] = array("b"=>"dole", "t"=>"górze", "bt"=>"dole i górze");
$prefsStrings["2.13"] = "Organizacja kolumn: ";
$prefsStrings["2.14"] = "kliknij tutaj";
$prefsStrings["2.15"] = "Poka¿ filtr/pasek szybkiego wyszukiwania";
$prefsStrings['2.16'] = 'W±tkuj wiadomo¶ci';
$prefsStrings["3.0"] = "Opcje Autozapisu";
$prefsStrings["3.1"] = "Zachowuj wys³ane wiadomo¶ci.";
$prefsStrings["3.2"] = "Zachowuj wiadomo¶ci wys³ane w folderze: ";
$prefsStrings["3.3"] = "";
$prefsStrings["3.4"] = "Automatycznie opró¿niaj kosz";
$prefsStrings["3.5"] = "Przenie¶ skasowane listy do folderu: ";
$prefsStrings["3.6"] = "";
$prefsStrings["3.7"] = "G³ówny katalog: ";
$prefsStrings["3.8"] = "Inne";
$prefsStrings["3.9"] = "Schowaj unsubscribed folders";
$prefsStrings["3.10"] = "Poka¿ zajêto¶æ skrzynki %m";
$prefsStrings["3.11"] = array(""=>"nie pokazuj", "m"=>"w li¶cie wiadomo¶ci", "f"=>"w li¶cie folderów");
$prefsStrings["3.12"] = "Folder roboczy";
$prefsStrings["4.0"] = "Opcje wy¶wietlania wiadomo¶ci";
$prefsStrings["4.1"] = "Ogl±daj w ramce";
$prefsStrings["4.2"] = "Koloruj cytaty";
$prefsStrings["4.3"] = "W³±czenie tej opcji mo¿e spowolniæ pracê systemu.";
$prefsStrings["4.4"] = "Zamieniaj adresy URL na odno¶niki";
$prefsStrings["4.5"] = "Poka¿ wiadomo¶ci HTML";
$prefsStrings["4.6"] = "Wklejaj obrazki";
$prefsStrings["4.7"] = "Poka¿ odno¶niki nawigacyjne";
$prefsStrings["4.8"] = "Niezaznaczaj wiadomo¶ci";
$prefsStrings['4.9'] = "Po usuniêciu/przeniesieniu, poka¿: %menu";
$prefsStrings['4.10']= array('main'=>"Folder",'next'=>'Nastêpny','prev'=>'Poprzedni');
$prefsStrings["5.0"] = "Podpis";
$prefsStrings["5.1"] = "Domy¶lne wstawianie podpisu";
$prefsStrings["5.2"] = "";
$prefsStrings["6.0"] = "Nowa wiadomo¶æ";
$prefsStrings["6.1"] = "Poka¿ ksi±¿kê adresow±";
$prefsStrings["6.2"] = "Poka¿ pola DW/UDW";
$prefsStrings["6.3"] = "Zamknij po wys³aniu";
$prefsStrings["6.4"] = "Komponuj wewn±trz ramki";
$prefsStrings["6.5"] = "Rozmiar pola tekstowego: ";
$prefsStrings['6.6'] = 'Domy¶lnie UDW';
$prefsStrings["7.0.0"] = "Dysk &amp; Opcje folderu";
$prefsStrings["7.0.1"] = "Opcje ograniczenia";
$prefsStrings["7.1"] = "Poka¿ liczbê nieprzeczytanych";
$prefsStrings["7.2"] = "Od¶wie¿aj listê folderów co %n sekund";
$prefsStrings['8.0'] = 'Interfejs u¿ytkownika';
$prefsStrings["8.1"] = 'Motyw';
$prefsStrings["8.2"] = "U¿ycie JavaScript";
$prefsStrings["8.3"] = "niskie";
$prefsStrings["8.4"] = "wysokie";
$prefsStrings['8.5'] = 'automatycznie';

$pref_col_title = "Organizacja kolumn";
$pref_colstr["order"] = "Kolejno¶æ";
$pref_colstr["field"] = "Pole";
$pref_col_label['c'] = "Zaznaczenie";
$pref_col_label['a'] = "Za³±czniki";
$pref_col_label['m'] = "Flagi/statusy";

$sort_fields=array("DATE"=>"Data", "SUBJECT"=>"Temat", "SIZE"=>"Rozmiar");
$sort_fields['INTERNALDATE'] = 'Otrzymano';
$sort_orders=array("ASC"=>"Rosn±co", "DESC"=>"Malej±co");

$sort_fields=array('DATE'=>'Wys³ano', 'SUBJECT'=>'Temat', 'SIZE'=>'Rozmiar');

$prefsButtonStrings = array( 0=> "Aktualizuj", 1=>"Zastosuj", 2=> "Anuluj", 3=> "Domy¶lne");

$prefs_new_user = "Wygl±da na to, ¿e logujesz sie po raz pierwszy...witaj!<br>";
$prefs_new_user .= "Proszê dokonaæ nastêpuj±cych ustawieñ, potem nacisn±æ \"Zastosuj\"";
?>
