<?php
/********************************************************
	lang/eng/pref_identities.inc
	(C)2004 Cezary Jackiewicz <cjackiewicz@poczta.onet.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_identities.inc");

$piStrings["identities"] = "To¿samo¶ci";
$piStrings["edit"] = "Zmodyfikuj";
$piStrings["name"] = "Nazwa";
$piStrings["email"] = "Email";
$piStrings["replyto"] = "Odpowied¼ do";
$piStrings["sig"] = "Podpis";
$piStrings["add"] = "Dodaj";
$piStrings["new"] = "Nowa to¿samo¶æ";
$piStrings["edit_ident"] = "Edycja to¿samo¶ci";
$piStrings["delete"] = "Usuñ";
$piStrings["setdef"] = "Zaznacz jako domy¶ln±";
$piStrings["isdef"] = "(domy¶lna)";

$piError[1] = "Wymagana jest nazwa lub email";

?>
