<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
	lang/pl/cp.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>
	(C)2004 Cezary Jackiewicz <cjackiewicz@poczta.onet.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings["0"] = "Dla ka¿dego elementu wprowad¼ kod koloru HTML.";
$pcStrings["0.1"] = "U¿yj ";
$pcStrings["0.2"] = "Tabeli Kolorów";
$pcStrings["0.3"] = " by znale¼æ w³a¶ciwe kody kolorów.";
$pcStrings["0.4"] = "Ustawienia które s± zale¿ne od motywu nie mog± zostaæ zmodyfikowane.";
$pcStrings["1.0"] = "Pasek narzêdziowy";
$pcStrings["2.0"] = "Lista folderów";
$pcStrings["3.0"] = "G³ówne";
$pcStrings["3.1"] = "T³o nag³ówka: ";
$pcStrings["3.2"] = "Tekst nag³ówka: ";
$pcStrings["3.3"] = "Ciemne t³o: ";
$pcStrings["3.4"] = "Jasny tekst: ";
$pcStrings["4.0"] = "Ró¿ne";
$pcStrings["4.1"] = "Cytaty: ";
$pcStrings["5.0"] = "Czcionki";
$pcStrings["5.1"] = "Rodzina czcionek";
$pcStrings["5.2"] = "Rozmiar czcionki: ";
$pcStrings["5.3"] = "Rozmiar czcionki ma³ej: ";
$pcStrings["5.4"] = "Rozmiar czcionki menu: ";
$pcStrings["5.5"] = "Rozmiar czcionki listy folderów: ";
$pcStrings["5.6"] = "Inna";

							
$pcPortions = array( "T³o: ", "Odno¶niki: ", "Tekst: ", "Pod¶wietlenie: ");

?>

