<?php
include("../lang/eng/quota.inc"); // <-- do not delete
/********************************************************
	lang/eng/quota.inc
	(C)2004 Cezary Jackiewicz <cjackiewicz@poczta.onet.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$quotaStr["label"] = "Wykorzystano: ";
$quotaStr["full"] = "%usedKB/%totalKB (%free% wolne)";
$quotaStr["unknown"] = "nieznane";

?>
