<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/pl/read_message.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>
	(C)2004,2005 Cezary Jackiewicz <cjackiewicz@poczta.onet.pl>
	
	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings[0] = "Poprzednia";
$rmStrings[1] = "Odpowiedz";
$rmStrings[2] = "Prze¶lij";
$rmStrings[3] = "Przywróæ";
$rmStrings[4] = "Usuñ";
$rmStrings[5] = "Plik";
$rmStrings[6] = "Czê¶ci";
$rmStrings[7] = "To jest wiadomo¶æ HTML. ";
$rmStrings[8] = "Naci¶nij tu by j± przeczytaæ.";
$rmStrings[9] = "¼ród³o";
$rmStrings[10] = "Rozmiar";
$rmStrings[11] = "Oznacz jako nieczytan±";
$rmStrings[12] = "nag³ówek";
$rmStrings[13] = "Poinformuj o spamie";
$rmStrings[14] = "Odpowiedz wszystkim";
$rmStrings[15] = "Odpowied¼ wys³ano";
$rmStrings[16] = "wersjê do wydruku";
$rmStrings[17] = 'Ta wiadomo¶æ jest zakodowana przy u¿yciu znaków spoza wybranego zestawu. Je¿eli wyst±pi³ problem z podgl±dem wiadomo¶ci, <a href="%url">kliknij tutaj</a>';
$rmStrings[18] = 'Ta wiadomo¶æ jest zakodowana przy u¿yciu nieznanego zestawu znaków. Je¿eli wyst±pi³ problem z podgl±dem wiadomo¶ci, nale¿y wybraæ inny zestaw znaków: %menu';
$rmStrings[19] = "Widok";
$rmStrings[20] = 'Czytaj';
$rmStrings[21] = 'Poka¿';
$rmStrings[22] = 'Akcja';
$rmStrings[23] = 'Wiadomo¶æ %message w w±tku';
$rmStrings[24] = 'Przenie¶ w±tek';
$rmStrings[25] = 'Znaleziony potencjalnie z³o¶liwy kod HTML zosta³ usuniêty z wiadomo¶ci.<br>';
$rmStrings[25].= 'Je¿eli ta wiadomo¶æ pochodzi z zaufanego ¼ród³a, <a href="%url">kliknij tutaj</a> aby zobaczyæ oryginaln± tre¶æ.';

$rmStrings['back'] = 'Wróæ';
$rmStrings['next'] = 'Nastêpny';
$rmStrings['previous'] = 'Poprzedni';
$rmStrings['newer'] = 'Nigdy';
$rmStrings['older'] = 'Starszy';

?>
