<?php
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/pl/search_errors.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>
	(C)2004 Cezary Jackiewicz <cjackiewicz@poczta.onet.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors["field"] = "B³êdne kryterium wyszukiwawcze:  B³êdne pole";
$searchErrors["empty"] = "B³êdne kryterium wyszukiwawcze:  Puste pole wyszukiwania";
$searchErrors["date"] = "B³êdne kryterium wyszukiwawcze:  Nieokre¶lona data";

?>