<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/es/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings[0] = "Regresar";
$rmStrings[1] = "Responder";
$rmStrings[2] = "Reenviar";
$rmStrings[3] = "Recuperar";
$rmStrings[4] = "Eliminar";
$rmStrings[5] = "Archivo";
$rmStrings[6] = "Partes";
$rmStrings[7] = "Éste es un mensaje HTML. ";
$rmStrings[8] = "Haz click aquí para leerlo.";
$rmStrings[9] = "Fuente";
$rmStrings[10] = "Tamaño";
$rmStrings[11] = "Marcar como no leído";
$rmStrings[12] = "Encabezado";
$rmStrings[13] = "Reportar Abuso (Spam)";
$rmStrings[14] = "Responder a todos";
$rmStrings[15] = "Contestación";
$rmStrings[16] = "Imprimir";
$rmStrings[17] = 'Este mensaje está codificado con un juego de caracteres diferentes al de sus preferencias. Si tiene problemas para ver este mensaje haga <a href="%url">click aquí</a>';
$rmStrings[18] = 'Este mensaje está codificado con un juego de caracteres no soportado. Si tiene problemas para ver este mensaje, intente con un juego alternativo de caracteres: %menu';
$rmStrings[19] = "Ver";
$rmStrings[20] = 'Marcar como leído';
$rmStrings[21] = 'Ver';
$rmStrings[22] = 'Acción';
$rmStrings[23] = 'Mensaje %message en conversación';
$rmStrings[24] = 'Mover conversación';

$rmStrings['back'] = 'Volver';
$rmStrings['next'] = 'Adelante';
$rmStrings['previous'] = 'Previo';
$rmStrings['newer'] = 'Nuevo';
$rmStrings['older'] = 'Anterior';

?>
