<?php
/********************************************************
	lang/gb/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	(C)2003 Lovell Fuller <iloha@lovell.info>
	(C)2005 Andrew Alderwick <andrew@alderwick.co.uk>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_contact.inc");

$ecStrings[8] = "Home Telephone";
$ecStrings[9] = "Work Telephone";
$ecStrings[10] = "Mobile Phone";
$ecStrings[17] = "Address";
$ecStrings[18] = "Town";
$ecStrings[19] = "County / Region";
$ecStrings[20] = "Postcode";

?>