<?php
/********************************************************
	lang/gb/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>
	(C)2005 Andrew Alderwick <andrew@alderwick.co.uk>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_identities.inc");


?>