<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/pl/edit_contact.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>
	(C)2004 Cezary Jackiewicz <cjackiewicz@poczta.onet.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings[0] = "Edytuj";
$ecStrings[1] = "Dodaj";
$ecStrings[2] = " Ksi±¿ka adresowa";
$ecStrings[3] = "Nazwa";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL";
$ecStrings[6] = "Grupa";
$ecStrings[7] = "Komentarze";
$ecStrings[8] = "Tel. domowy";
$ecStrings[9] = "Tel. s³u¿bowy";
$ecStrings[10] = "Tel. komórkowy";
$ecStrings[11] = "Adres";
$ecStrings[12] = "Drugi Email";
$ecStrings[13] = "Usuñ";
$ecStrings[14] = "Inne";
$ecStrings[15] = "Imiê";
$ecStrings[16] = "Nazwisko";
$ecStrings[17] = "Ulica";
$ecStrings[18] = "Miasto";
$ecStrings[19] = "Region";
$ecStrings[20] = "Kod pocztowy";
$ecStrings[21] = "Kraj";
$ecStrings[22] = "Anuluj";
$ecStrings[23] = 'URL Kalendarza';
$ecStrings[24] = 'RSS/Atom';

$errors[0] = "Nie mogê dodaæ wpisu:  b³±d bazy danych.";
$errors[1] = "Istnieje ju¿ wpis o podanym adresie.";
$errors[2] = "Naci¶nij ";
$errors[3] = "tutaj";
$errors[4] = " by zmodyfikowaæ wpis.";
$errors[5] = "Osoba nie zosta³a odnaleziona, lub brak dostêpu.";
$errors[6] = "Czy na pewno chcesz usun±æ wpis dla \"";
$errors[7] = "\"?";

?>
