<?php 
/********************************************************
	lang/en/login.inc
	(C)2004 Cezary Jackiewicz <cjackiewicz@poczta.onet.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="Login";
$loginStrings[1]="Has³o";
$loginStrings[2]="Serwer";
$loginStrings[3]="Typ";
$loginStrings[4]="Katalog g³ówny";
$loginStrings[5]="Jêzyk";
$loginStrings[6]="OK";

$loginErrors[0]="Niedozwolony host";
$loginErrors[1]="B³±d: katalog \"uploads\" nie istnieje";
$loginErrors[2]="B³±d: katalog \"users\" nie istnieje";
$loginErrors[3]="B³±d: katalog \"sessions\" nie istnieje ";

?>
