<?php 
/********************************************************
	lang/en/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="Όνομα Χρήστη";
$loginStrings[1]="Κωδικός";
$loginStrings[2]="Εξυπηρετητής";
$loginStrings[3]="Τύπος";
$loginStrings[4]="Ριζικός κατάλογος";
$loginStrings[5]="Γλώσσα";
$loginStrings[6]="Είσοδος";

$loginErrors[0]="Μη εξουσιοδοτημένος διακομιστής";
$loginErrors[1]="Σφάλμα: Ο κατάλογος \"uploads\"  δεν βρέθηκε";
$loginErrors[2]="Σφάλμα: Ο κατάλογος \"users\"  δεν βρέθηκε";
$loginErrors[3]="Σφάλμα: Ο κατάλογος \"sessions\"  δεν βρέθηκε";

?>
