<?php
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_identities.inc");

$piStrings["identities"] = "Ταυτότητες";
$piStrings["edit"] = "Σύνταξη";
$piStrings["name"] = "Όνομα";
$piStrings["email"] = "Ηλεκτρονική Διεύθυνση";
$piStrings["replyto"] = "Απάντηση-πρός";
$piStrings["sig"] = "Υπογραφή";
$piStrings["add"] = "Προσθήκη";
$piStrings["new"] = "Νέα Ταυτότητα";
$piStrings["edit_ident"] = "Σύνταξη Ταυτότητας";
$piStrings["delete"] = "Διαγραφή";
$piStrings["setdef"] = "Ορισμός ως εξ'ορισμού";
$piStrings["isdef"] = "(Εξ'ορισμού)";

$piError[1] = "Χρειάζεται όνομα ή ηλεκτρονική διεύθυνση";

?>
