<?php
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/read_message.inc");


$rmStrings[0] = "Ευρετήριο";
$rmStrings[1] = "Απάντηση";
$rmStrings[2] = "Προώθηση";
$rmStrings[3] = "Ακύρωση διαγραφής";
$rmStrings[4] = "Διαγραφή";
$rmStrings[5] = "Μετακίνηση";
$rmStrings[6] = "Μέρη";
$rmStrings[7] = "Αυτή είναι μια επιστολή HTML. ";
$rmStrings[8] = "Πατήστε εδώ για να τη διαβάσετε.";
$rmStrings[9] = "Πηγαίος κώδικας";
$rmStrings[10] = "Μέγεθος";
$rmStrings[11] = "Μη διαβασμένο";
$rmStrings[20] = 'Διαβασμένο';
$rmStrings[12] = "Εμφάνιση κεφαλίδων";
$rmStrings[13] = "Αναφορά παρενοχλητικής επιστολής";
$rmStrings[14] = "Απ. σε ΟΛΟΥΣ";
$rmStrings[15] = "Απαντημένο";
$rmStrings[16] = "Εκτύπωση";
$rmStrings[17] = 'Αυτή η επιστολή είναι κωδικοποιημένη με χαρακτήρες διαφορετικούς από το προτιμώμενό σας σύνολο χαρακτήρων. Εαν έχετε προβλήματα στο να δείτε τη παρακάτω επιστολή, <a href="%url">πατήστε εδώ</a>';
$rmStrings[18] = 'Αυτή η επιστολή είναι κωδικοποιημένη με μη υποστηριζόμενο σύνολο χαρακτήρων. Εαν έχετε προβλήματα στο να δείτε την επιστολή, δοκιμάστε κάποιο εναλλακτικό σύνολο χαρακτήρων: %menu';
$rmStrings[19] = "Εμφάνιση";
?>
