<?php
/********************************************************
	lang/eng/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/tool.inc");

$toolStrings["folders"] 	= "Φάκελοι";
$toolStrings["inbox"] 	= "Εισερχόμενα";
$toolStrings["compose"] 	= "Σύνθεση";
$toolStrings["calendar"] 	= "Ημερολόγιο";
$toolStrings["contacts"] 	= "Επαφές";
$toolStrings["bookmarks"] 	= "Σελιδοδείκτες";
$toolStrings["search"] 	= "Αναζήτηση";
$toolStrings["prefs"] 	= "Επιλογές";
$toolStrings["logout"] 	= "Έξοδος";
$toolStrings["go"] 	= "Φύγαμε";

?>
