<?php
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
	lang/cat/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings[0] = "Asumpte";
$composeHStrings[1] = "De";
$composeHStrings[2] = "Per a";
$composeHStrings[3] = "Copia";
$composeHStrings[4] = "Copia Oculta";
$composeHStrings[5] = "Data";


$composeStrings[0] = "Escriure Missatge";
$composeStrings[1] = "Enviar Missatge";
$composeStrings[2] = "Pujar";
$composeStrings[3] = "Agregar Firma";
$composeStrings[4] = "Adjuntar";
$composeStrings[5] = "Mostrar Contactes";
$composeStrings[6] = "Ocultar Contactes";
$composeStrings[7] = "Cos del missatge:";
$composeStrings[8] = "Inserir";
$composeStrings[9] = "Amb data %d, %s va escriure:\n";
$composeStrings[10] = "--- Missatge Original ---\n";
$composeStrings[11] = "Close Window";


$composeErrors[0] = "El camp \"Assumpte\" est&agrave; buit.  Si us plau escriu un assumpte.";
$composeErrors[1] = "El camp \"De\" est&agrave; buit.  Si us plau, omple'l amb la teva direcci&oacute; de correu electr&ograve;nic.";
$composeErrors[2] = "El camp \"Per a\" est&agrave; buit.  Si us plau, especifica la direcci&oacute; de dest&iacute;.";
$composeErrors[3] = "Error al pujar l'arxiu";
$composeErrors[4] = "No s'han rebut fitxers.";
$composeErrors[5] = "Per a prevenir el correu no dessitjat, tan sols pots enviar a %1 persones (%2 en total per sesi&oacute;) cada %3 segons.";

?>
