<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/cat/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings[0] = "Contactes";
$cStrings[1] = "Inserir Contacte";
$cStrings[2] = " Contacte";
$cStrings[3] = "Nom";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Grup";
$cStrings[7] = "Comentaris";
$cStrings[8] = "Inserir/Editar Contacte";
$cStrings[9] = "Email";
$cStrings[10] = "Compose";


$cErrors[0] = "La llista de contactes &eacute;s buida";

?>
