<?php
include("../lang/eng/dates.inc"); // <-- do not delete
/********************************************************
	lang/cat/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_datetime["dsow"] = array ("Diu","Dil","Dim","Dim","Dij","Div","Dis");
$lang_datetime["today"] = "Avui %t";
$lang_datetime["lastweek"] = "%w %t";
$lang_datetime["thisyear"] = "%d/%m";
$lang_datetime["prevyears"] = "%d/%m/%y";


?>