<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
	lang/cat/pref_colors.inc	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	This file is part of IlohaMail, and released under GPL.	See COPYING,
	or http://www.fsf.org/copyleft/gpl.html
********************************************************/
$pcStrings["0"] = "posa el codi de color HTML per cada component.";
$pcStrings["0.1"] = "Usa el ";
$pcStrings["0.2"] = "gr&agrave;fic de colors de codi";
$pcStrings["0.3"] = " per trobar el codi de color correcte.";
$pcStrings["1.0"] = "Barra d'eines";
$pcStrings["2.0"] = "Llista de Carpetes";
$pcStrings["3.0"] = "Principal";
$pcStrings["4.0"] = "miscel&middot;lani";
$pcStrings["4.1"] = "Cites: ";

$pcPortions = array( "Fons: ", "Vincles: ", "Text: ", "Remarcat: ");
?>
