<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/cat/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings[0] = "Regressar";
$rmStrings[1] = "Respondre";
$rmStrings[2] = "Reexpedir";
$rmStrings[3] = "Recuperar";
$rmStrings[4] = "Eliminar";
$rmStrings[5] = "Arxiu";
$rmStrings[6] = "Parts";
$rmStrings[7] = "Aquest &eacute;s un missatge HTML. ";
$rmStrings[8] = "Fes clic aqu&iacute; per a llegir-lo.";
$rmStrings[9] = "Font";
$rmStrings[10] = "Grand&agrave;ria";
$rmStrings[11] = "Marcar com no llegit";
$rmStrings[12] = "Mostrar encap&ccedil;alat";
$rmStrings[13] = "Reportar Ab&uacute;s (Spam)";
$rmStrings[14] = "Respondre a tots";

?>
