<?php
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/cat/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors["field"] = "Criteri de recerca inv&agrave;lid: Camp no v&agrave;lid";
$searchErrors["empty"] = "Criteri de recerca inv&agrave;lid: Cadena de recerca buida";
$searchErrors["date"] = "Criteri de recerca inv&agrave;lid: No es va especificar data";

?>
