<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/cat/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings["folders"] = "Carpetes";
$toolStrings["inbox"] = "Safata d'Entrada";
$toolStrings["compose"] = "Redactar";
$toolStrings["contacts"] = "Contactes";
$toolStrings["search"] = "Cercar";
$toolStrings["prefs"] = "Prefer&egrave;ncies";
$toolStrings["logout"] = "Sortir";
$toolStrings["go"] = "Anar";

?>
