<?php
/********************************************************
	lang/eng/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Stefan Pettersson <stefan@pezzen.org>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_contact.inc");

$ecStrings[0] = "Redigera";
$ecStrings[1] = "Lägg till";
$ecStrings[2] = " Kontakt";
$ecStrings[3] = "Namna";
$ecStrings[4] = "Email";
$ecStrings[5] = "URI";
$ecStrings[6] = "Grupp";
$ecStrings[7] = "Kommentarer";
$ecStrings[8] = "Telefon Hem";
$ecStrings[9] = "Telefon Arbete";
$ecStrings[10] = "Mobil";
$ecStrings[11] = "Adress";
$ecStrings[12] = "Alt. Email";
$ecStrings[13] = "Radera";
$ecStrings[14] = "Annat";
$ecStrings[15] = "Förnamn";
$ecStrings[16] = "Efternamn";
$ecStrings[17] = "Gata";
$ecStrings[18] = "Stad";
$ecStrings[19] = "Stat/Region";
$ecStrings[20] = "Postnr";
$ecStrings[21] = "Land";


$errors[0] = "Kunde inte lägga till kontakten på grund av databasproblem.";
$errors[1] = "En kontakt med den adressen finns redan.";
$errors[2] = "Klicka ";
$errors[3] = "här";
$errors[4] = " för att redigera kontakten istället.";
$errors[5] = "Hittade inte kontakten eller ingen åtkomst.";
$rors[6] = "Är du säker på att du vill radera kontakten\"";
$errors[7] = "\"?";

?>