<?php
/********************************************************
	lang/eng/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Stefan Pettersson <stefan@pezzen.org>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/main.inc");

$mainMessages["delete"] = "Delete %n message(s)";
$mainMessages["move"] = "Moved %n message(s) to %f";

$mainStrings[0] = "Visar %p av %n";
$mainStrings[1] = " meddelande i mappen";
$mainStrings[2] = "Föregående";
$mainStrings[3] = " meddelanden";
$mainStrings[4] = "Nästa";
$mainStrings[5] = " Meddelanden";
$mainStrings[6] = "Ämne";
$mainStrings[7] = "Till";
$mainStrings[8] = "Från";
$mainStrings[9] = "Datum";
$mainStrings[10] = "Ta bort";
$mainStrings[11] = "Töm Skräp";
$mainStrings[12] = "Flytta";
$mainStrings[13] = "Sök";
$mainStrings[14] = "Storlek";
$mainStrings[15] = "namnlös";
$mainStrings[16] = "Visa";
$mainStrings[17] = "Titta efter nya mail";
$mainStrings[18] = "Ta bort alla mail i mappen";
$mainStrings[19] = "Avbryt";
$mainStrings[20] = "Markera som %b";
$mainStrings[21] = "Läst";
$mainStrings[22] = "Oläst";
$mainStrings[23] = "Välj...";
$mainStrings[24] = "Kör filter";
$mainStrings[25] = "Markera";
$mainStrings[26] = "Viktigt!";
$mainStrings[27] = "Filter:";
$mainStrings[28] = "Alla Filter";
$mainStrings[29] = "Kör";
$mainStrings[30] = "Snabbsök:";
$mainStrings[31] = "Välj";


$mainErrors[0] = "Inga meddelanden hittade i denna mapp";
$mainErrors[1] = "Inga meddelanden i denna mapp";
$mainErrors[2] = "Kunde inte flytta meddelanden till skräpmappen.";
$mainErrors[3] = "Kunde inte markera meddelanden som raderade.";
$mainErrors[4] = "Kunde inte flytta meddelanden.";
$mainErrors[5] = "Skräp-mapp ej angiven.";
$mainErrors[6] = "Kunde inte tömma skräpmappen";
$mainErrors[7] = "Är du säker på att du vill ta bort ALLA meddelanden i %f?";
$mainErrors[8] = "Klicka på pilarna under kolumntitlarna för att flytta dem.<br>Stäng fönstret när du är färdig.";

?>