<?php
include("../lang/eng/edit_folders.inc"); // <-- do not delete
/********************************************************
	lang/eng/edit_folders.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings[0] = "Gestion des dossiers";
$efStrings[1] = "Ajouter un dossier";
$efStrings[2] = "Cr&#233;er un dossier: ";
$efStrings[3] = "Ajouter";
$efStrings[4] = "Supprimer un dossier";
$efStrings[5] = "Supprimer";
$efStrings[6] = "Renommer un dossier";
$efStrings[7] = "Renommer";
$efStrings[8] = "S&#233;lection";
$efStrings[9] = "S'abonner";
$efStrings[10] = "Liste";
$efStrings[11] = "Se d&#233;sabonner";

$errors[0] = "Dossier ajout&#233;: ";
$errors[1] = "Impossible de cr&#233;er le dossier: ";
$errors[2] = "Dossier supprim&#233;: ";
$errors[3] = "Impossible de supprimer le dossier: ";
$errors[4] = "Dossier renomm&#233;: ";
$errors[5] = "Impossible de renommer le dossier: ";
$errors[6] = "La gestion des dossiers n'est possible qu'avec le protocole IMAP.";

?>
