<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "新規スケジュール";
$calStr["edit_schedule"] = "スケジュールを更新";
$calStr["weekof"] = "%dの週";
$calStr["title"] = "タイトル:";
$calStr["color"] = "表示色:";

$calStr["color_names"]['Dark Red'] = '濃い赤';
$calStr["color_names"]['Red'] = '赤';
$calStr["color_names"]['Deep Blue'] = '紺';
$calStr["color_names"]['Blue'] = '青';
$calStr["color_names"]['Dark Green'] = '濃い緑';
$calStr["color_names"]['Green'] = '緑';
$calStr["color_names"]['Purple'] = '紫';
$calStr["color_names"]['Cyan'] = 'シアン';
$calStr["color_names"]['Orange'] = 'オレンジ';
$calStr["color_names"]['Yellow'] = '黄色';
$calStr["color_names"]['Magenta'] = 'マゼンタ';
$calStr["color_names"]['No Color'] = '無し';

$calStr["starts"] = "開始日:";
$calStr["ends"] = "終了日:";
$calStr["from"] = "開始時間:";
$calStr["until"] = "終了時間:";
$calStr["repeat_on"] = "繰り返し";
$calStr["of"] = "毎月：";
$calStr["weeks"] = array(1=>"第一週", 2=>"第二週", 3=>"第三週", 4=>"第四週"); 
$calStr["week_blurb"] = "未指定の場合は終了日まで毎週繰り返します。";
$calStr["monthly"] = "毎月繰り返す";
$calStr["yearly"] = "毎年繰り返す";
$calStr["place"] = "場所:";
$calStr["description"] = "コメント:";
$calStr["add"] = "追加";
$calStr["update"] = "更新";
$calStr["Delete"] = "削除";
$calStr["go"] = "表示";
$calStr["public"] = "共有する";
$calStr['no schedules'] = '<p>この週のスケジュールは現在空白です。<br>新しい項目を記入するには、上の日付にクリックしてください。';
$calStr['all day'] = "終日";
$calStr['is all day'] = '終日イベント';
?>