<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/jp/read_message.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	PURPOSE:
		Provide strings for "source/read_message.inc"

********************************************************/

$rmStrings[0] = "戻る";
$rmStrings[1] = "返信";
$rmStrings[2] = "転送";
$rmStrings[3] = "ゴミ箱から出す";
$rmStrings[4] = "消去";
$rmStrings[5] = "移動";
$rmStrings[6] = "てん付";
$rmStrings[7] = "このメッセージはHTML形式になってます。";
$rmStrings[8] = "ここにクリックすると開きます";
$rmStrings[9] = "ソース";
$rmStrings[10] = "容量";
$rmStrings[11] = "未読";
$rmStrings[12] = "ヘッダー";
$rmStrings[13] = "スパム報告";
$rmStrings[14] = "全員へ返信";
$rmStrings[15] = "返信済み";
$rmStrings[16] = "プリント版";
$rmStrings[17] = 'このメッセージは選択された文字コードとは別の文字コードでエンコードされています。文字化けした場合は<a href="%url">ここにクリックしてください。</a>';
$rmStrings[18] = 'このメッセージの文字コードを認識できませんでした。表示文字コードを選択してください：%menu';
$rmStrings[19] = "表示";
$rmStrings[20] = '該読';
$rmStrings[21] = "表示";
$rmStrings[22] = 'アクション';

$rmStrings['back'] = 'リスト表示';
$rmStrings['next'] = '次';
$rmStrings['previous'] = '前';
$rmStrings['newer'] = 'より新しい';
$rmStrings['older'] = 'より古い';

?>