<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/hu/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings[0] = "Ir";
$ecStrings[1] = "Hozzáad";
$ecStrings[2] = " Címjegyzék ";
$ecStrings[3] = "Név";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL (Web-Cím";
$ecStrings[6] = "Csoport";
$ecStrings[7] = "Megjegyzések";
$ecStrings[8] = "Otthoni telefonszám";
$ecStrings[9] = "Munkahelyi telefonszám";
$ecStrings[10] = "Mobil telefonszám";
$ecStrings[11] = "Lakcím";
$ecStrings[12] = "Másik Email";
$ecStrings[13] = "Törlés";
$ecStrings[14] = "Egyéb";


$errors[0] = "Nem tudtuk a címet bejegyezni - adatbázis hiba.";
$errors[1] = "Ez a cím már be van jegyezva.";
$errors[2] = "Kattintson ";
$errors[3] = "ide";
$errors[4] = " a bejegyzést megirni.";
$errors[5] = "Ismeretlen vagy visszautasított cím.";
$errors[6] = "Biztos abban hogy törölni kívánja\"";
$errors[7] = "\"?";

?>