<?php
/********************************************************
	lang/eng/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/compose.inc");

$composeHStrings[0] = "Pøedmìt";
$composeHStrings[1] = "Od";
$composeHStrings[2] = "Komu";
$composeHStrings[3] = "Kopie";
$composeHStrings[4] = "Skrytá kopie";
$composeHStrings[5] = "Datum";


$composeStrings[0] = "Vytvoøení zprávy";
$composeStrings[1] = "Odeslat zprávu";
$composeStrings[2] = "Pøipojit";
$composeStrings[3] = "Pøipojit podpis";
$composeStrings[4] = "Pøíloha";
$composeStrings[5] = "Kontakty";
$composeStrings[6] = "Skrýt kontakty";
$composeStrings[7] = "Text zprávy:";
$composeStrings[8] = "Pøidat";
$composeStrings[9] = "Dne %d, napsal %s:\n";
$composeStrings[10] = "--- Pùvodní zpráva ---\n";
$composeStrings[11] = "Zavøít okno";

$composeStrings[12] = "Kontrola pravopisu";
$composeStrings[13] = "Opravit pravopis";
$composeStrings[14] = "Beze zmìn";
$composeStrings[15] = "Mo¾né chyby pøi kontrole pravopisu";
$composeStrings[16] = "Zmìny v pravopisu";
$composeStrings[17] = "ignorovat";
$composeStrings[18] = "smazat";
$composeStrings[19] = "Pøidat adresu do skrýté";

$composeStrings["title"] = "Vytvoøení zprávy";
$composeStrings["save"] = "Ulo¾it";

$composeErrors[0] = "Pole Pøedmìt je prázdné. Prosím vlo¾te Pøedmìt nebo opìt klepnìte na \"".$composeStrings[1]."\" pro odeslání zprávy.";
$composeErrors[1] = "Pole \"Od\" je prázdné. Prosím vlo¾te svou emailovou adresu.";
$composeErrors[2] = "Pole \"Komu\" je prázdné. Prosím vlo¾te emailovou adresu pøíjemce.";
$composeErrors[3] = "Upload souboru selhal.";
$composeErrors[4] = "®ádné soubory .";
$composeErrors[5] = "Kvùli prevenci pøed SPAMem, mù¾ete odeslat zprávu %1 lidem (celkem %2 na jedno pøihlá¹ení) ka¾dých %3 vteøin.";

$composeErrors[6] = "Kontrola pravopisu neshledala ¾ádných chyb.";
$composeErrors[7] = "Kontrola pravopisu pro uvedený jazyk není dostupná.";
$composeErrors[8] = "(pou¾itý slovník: %s)";
?>
