<?php
/********************************************************
	lang/eng/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/contacts.inc");

$cStrings[0] = "Kontakty";
$cStrings[1] = "Nový kontakt";
$cStrings[2] = " Kontakt";
$cStrings[3] = "Jméno";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Skupina";
$cStrings[7] = "Poznámka";
$cStrings[8] = "Nový/Uprav Kontakt";
$cStrings[9] = "Email";
$cStrings[10] = "Vytvoøit zprávu";

$cStrings["close"] = "Zavøít okno";
$cStrings["addto"] = "Pøidat kontakty do %s";
$cStrings["showgrp"] = "Zobraz %s";
$cStrings["all"] = "V¹e";
$cStrings["instructions"] = "Klepnìte na jméno pro pøidání. Také mù¾ete klepnout na název skupiny pro pøidání v¹ech v této skupinì.";
$cStrings["share"] = "Oznaèit záznam jako veøejný";
$cStrings["add_contact"] = "Pøidat kontakt";
$cStrings["edit_contact"] = "Upravit kontakt";
$cStrings["add"] = "Pøidat";
$cStrings["edit"] = "Upravit";
$cStrings["export"] = "Exportovat";
$cStrings["import"] = "Importovat";
$cStrings["exportall"] = "Exportovat v¹echny záznamy";
$cStrings["exportgroups"] = "Exportovat skupiny";
$cStrings["exportentries"] = "Exportovat záznamy";
$cStrings["format"] = "Format";
$cStrings["filename"] = "Jméno souboru";

$cErrors[0] = "Vá¹ seznam kontaktù je prázdný";
$cErrors[1] = "Nemù¾u pøistoupit k urèenému záznamu.";


?>
