<?php
/********************************************************
	lang/no/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Tor Olsen  <tor@monet.no>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Bokmerker";
$bmStrings["identities"] = "Identiteter";
$bmStrings["edit"] = "Redigere";
$bmStrings["name"] = "Navn";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Kategori";
$bmStrings["other"] = "Spesifiser-&gt;";
$bmStrings["comments"] = "Kommentarer";
$bmStrings["add"] = "Legg till";
$bmStrings["new"] = "Ny post";
$bmStrings["edit_url"] = "Rediger post";
$bmStrings["delete"] = "Slett";

$bmError[1] = "Navn eller URL kreves";
$bmError[2] = "Denne funksjon er ikke aktivert.";

?>
