<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
	lang/no/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Tor Olsen <tor@monet.no>
********************************************************/

$pcStrings["0"] = "Legg til en HTML fargekode for hver komponent.";
$pcStrings["0.1"] = "Bruk ";
$pcStrings["0.2"] = "Fargekode kartet";
$pcStrings["0.3"] = " for å finne de riktige fargekodene.";
$pcStrings["1.0"] = "Verktøylinjen";
$pcStrings["2.0"] = "Mappeliste";
$pcStrings["3.0"] = "Hoved";
$pcStrings["4.0"] = "Forskjellig";
$pcStrings["4.1"] = "Sitater: ";
$pcStrings["5.0"] = "Fonter";
$pcStrings["5.1"] = "Fontfamilie";
$pcStrings["5.2"] = "Fontstørrelse: ";
$pcStrings["5.3"] = "Liten Fontstørrelse: ";
$pcStrings["5.4"] = "Fontstørrelse i menyer: ";
$pcStrings["5.5"] = "Fontstørrelse i mappelisten: ";


							
$pcPortions = array( "Bakgrunn: ", "Lenker: ", "Tekst: ", "Markering: ");

?>
