<?php
include("../lang/eng/pref_identities.inc"); // <-- do not delete
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

         Translated by Tor Olsen <tor@monet.no>

********************************************************/

$piStrings["identities"] = "Identiteter";
$piStrings["edit"] = "Rediger";
$piStrings["name"] = "Navn";
$piStrings["email"] = "Epost";
$piStrings["replyto"] = "Send svar til";
$piStrings["sig"] = "Signatur";
$piStrings["add"] = "Legg til";
$piStrings["new"] = "Ny identitet";
$piStrings["edit_ident"] = "Rediger identitet";
$piStrings["delete"] = "Slett";
$piStrings["setdef"] = "Velg som standard";
$piStrings["isdef"] = "(Standard)";


$piError[1] = "Du må oppgi navn eller epost";

?>
