<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
        lang/dk/edit_contact.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated by Torben Rybner, Ziberex (try@ziberex.dk)
	          and Niels Baggesen <nba@users.sourceforge.net>

********************************************************/

$ecStrings[0] = "Rediger";
$ecStrings[1] = "Tilf&oslash;j";
$ecStrings[2] = " kontaktperson";
$ecStrings[3] = "Navn";
$ecStrings[4] = "E-post";
$ecStrings[5] = "URL";
$ecStrings[6] = "Gruppe";
$ecStrings[7] = "Kommentar";
$ecStrings[8] = "Hjemmetelefon";
$ecStrings[9] = "Arbejdstelefon";
$ecStrings[10] = "Mobiltelefon";
$ecStrings[11] = "Adresse";
$ecStrings[12] = "Alt. e-post";
$ecStrings[13] = "Slet";
$ecStrings[14] = "Andet";
$ecStrings[15] = "Fornavn";
$ecStrings[16] = "Efternavn";
$ecStrings[17] = "Gade";
$ecStrings[18] = "By";
$ecStrings[19] = "Stat / Region";
$ecStrings[20] = "Postnr";
$ecStrings[21] = "Land";
$ecStrings[22] = "Afbryd";
$ecStrings[23] = 'Kalender URL';
$ecStrings[24] = 'RSS/Atom';

$errors[0] = "Kunne ikke tilf&oslash;je kontaktperson: Databasefejl.";
$errors[1] = "Der findes allerede en indgang med samme adresse.";
$errors[2] = "Klik ";
$errors[3] = "her";
$errors[4] = " for i stedet at redigere den indgang.";
$errors[5] = "Kontaktperson ikke fundet eller adgang n&aelig;gtet.";
$errors[6] = "Er du sikker p&aring;, at du vil slette \"";
$errors[7] = "\"?";

?>
