<?php
include("../lang/eng/folders.inc"); // <-- do not delete
/********************************************************
        lang/dk/folders.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

        $fl_str["folders"] = "Foldere";
        $fl_str["manage"] = "H&aring;ndtering af foldere";

        $defaults["INBOX"] = "Indbakke";
        $defaults[$sentbox] = "Sendt post";
        $defaults[$trashname] = "Papirkurv";
        $defaults[$draftbox] = "Kladder";
        $fstr["reload"] = "genl&aelig;s";
        $fstr["expunge"] = "t&oslash;m";

?>
