<?php 
/********************************************************
	lang/<lang>/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

 	Translated by Niels Baggesen <nba@users.sourceforge.net>
 
********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="Brugernavn";
$loginStrings[1]="Kodeord";
$loginStrings[2]="Server";
$loginStrings[3]="Type";
$loginStrings[4]="Rootdir";
$loginStrings[5]="Sprog";
$loginStrings[6]="Log p&aring;";

$loginErrors[0]="Ikke acceptabel server";
$loginErrors[1]="Error: \"uploads\" directory not found";
$loginErrors[2]="Error: \"users\" directory not found";
$loginErrors[3]="Error: \"sessions\" directory not found";

?>