<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
    lang/dk/cp.inc
    (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

    This file is part of IlohaMail, and released under GPL.
    See COPYING, or http://www.fsf.org/copyleft/gpl.html

    Translated by Torben Rybner, Ziberex (try@ziberex.dk)
              and Niels Baggesen <nba@users.sourceforge.net>

********************************************************/

$pcStrings["0"] = "Indtast en HTML farve for hvert komponent.";
$pcStrings["0.1"] = "Brug ";
$pcStrings["0.2"] = "oversigten over farvekoder";
$pcStrings["0.3"] = " for at finde farvekoderne.";
$pcStrings["0.4"] = "Indstillinger der indg&aring;r i dit tema kan ikke &aelig;ndres";

$pcStrings["1.0"] = "V&aelig;rkt&oslash;jslinie";

$pcStrings["2.0"] = "Oversigt over foldere";

$pcStrings["3.0"] = "Hovedbilledet";
$pcStrings["3.1"] = "Overskrift baggrund: ";
$pcStrings["3.2"] = "Overskrift tekst: ";
$pcStrings["3.3"] = "M&oslash;rk baggrund: ";
$pcStrings["3.4"] = "Lys tekst: ";

$pcStrings["4.0"] = "Diverse";
$pcStrings["4.1"] = "Citater: ";

$pcStrings["5.0"] = "Fonte";
$pcStrings["5.1"] = "Fontfamilie";
$pcStrings["5.2"] = "Fontst&oslash;rrelse: ";
$pcStrings["5.3"] = "Lille fontst&oslash;rrelse: ";
$pcStrings["5.4"] = "Menu fontst&oslash;rrelse: ";
$pcStrings["5.5"] = "Folderliste fontst&oslash;rrelse: ";
$pcStrings["5.6"] = "Alternativ font: ";

$pcPortions[0] = "Baggrund: ";
$pcPortions[1] = "Links: ";
$pcPortions[2] = "Tekst: ";
$pcPortions[3] = "Fremh&aelig;v: ";

?>
