<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
        lang/dk/read_message.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Torben Rybner, Ziberex (try@ziberex.dk)
	          and Niels Baggesen <nba@users.sourceforge.net>

********************************************************/

$rmStrings[0] = "Tilbage";
$rmStrings[1] = "Svar";
$rmStrings[2] = "Videresend";
$rmStrings[3] = "Fortryd slet";
$rmStrings[4] = "Slet";
$rmStrings[5] = "Flyt til";
$rmStrings[6] = "Dele";
$rmStrings[7] = "Dette er en HTML meddelelse. ";
$rmStrings[8] = "Klik her for at l&aelig;se den.";
$rmStrings[9] = "Vis den r&aring; meddelelse";
$rmStrings[10] = "St&oslash;rrelse";
$rmStrings[11] = "Marker som ul&aelig;st";
$rmStrings[12] = "Vis brevhovede";
$rmStrings[13] = "Rapporter spam";
$rmStrings[14] = "Svar til alle";
$rmStrings[15] = "Besvaret";
$rmStrings[16] = "Udskriv";
$rmStrings[17] = 'Denne meddelelse er kodet med et andet tegns&aelig;t end dit foretrukne. Hvis du har problemer med at l&aelig;se meddelelsen, s&aring; <a href="%url">klik her</a>';
$rmStrings[18] = 'Denne meddelelse er kodet i et tegns&aelig;t der ikke er underst&oslash;ttet. Hvis du har problemer med at l&aelig;se den, s&aring; pr&oslash;v et andet: %menu';
$rmStrings[19] = "Vis";
$rmStrings[20] = "l&aelig;s";
$rmStrings[21] = "Vis";
$rmStrings[22] = "Udf&oslash;r";
$rmStrings[23] = "Meddelelse %message i tr&aring;den";
$rmStrings[24] = "Flyt tr&aring;d";

$rmStrings['back'] = 'Tilbage';
$rmStrings['next'] = 'N&aelig;ste';
$rmStrings['previous'] = 'Forrige';
$rmStrings['newer'] = 'Nyere';
$rmStrings['older'] = '&AElig;ldre';
?>
