<?php
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
	lang/es/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings[0] = "Asunto";
$composeHStrings[1] = "De";
$composeHStrings[2] = "Para";
$composeHStrings[3] = "Copia";
$composeHStrings[4] = "Copia Oculta";
$composeHStrings[5] = "Fecha";


$composeStrings[0] = "Redactar Mensaje";
$composeStrings[1] = "Enviar Mensaje";
$composeStrings[2] = "Subir";
$composeStrings[3] = "Agregar Firma";
$composeStrings[4] = "Adjuntar";
$composeStrings[5] = "Mostrar Contactos";
$composeStrings[6] = "Ocultar Contactos";
$composeStrings[7] = "Cuerpo del mensaje";
$composeStrings[8] = "A&ntilde;adir";
$composeStrings[9] = "Con fecha %d, %s escribió:\n";
$composeStrings[10] = "--- Mensaje Original ---\n";
$composeStrings[11] = "Cerrar ventana";

$composeStrings[12] = "Revisar Ortografía";
$composeStrings[13] = "Corregir Texto";
$composeStrings[14] = "Sin Cambios";
$composeStrings[15] = "Posibles Errores Ortográficos";
$composeStrings[16] = "Cambios en el Texto";
$composeStrings[17] = "ignorar";
$composeStrings[18] = "borrar";
$composeStrings[19] = 'Enviar Copia Oculta a esta dirección';

$composeStrings["title"] = "Redactar Mensaje";
$composeStrings['save'] = 'Guardar';

$composeErrors[0] = "El campo del asunto está vacío.  Por favor, escribe un asunto.";
$composeErrors[1] = "El campo \"de\" está vacío.  Por favor, introduce tu dirección de correo electrónico.";
$composeErrors[2] = "El campo \"Para\" está vacío.  Por favor, especifica la dirección de destino.";
$composeErrors[3] = "Fallo al subir archivo";
$composeErrors[4] = "No se recibieron archivos.";
$composeErrors[5] = "Para prevenir el correo no deseado, solamente puedes enviar a %1 personas (%2 en total por sesión) cada %3 segundos.";

$composeErrors[6] = "No se encontraron errores ortográficos.";
$composeErrors[7] = "No está disponible el chequeo de ortografía para el lenguaje indicado.";
$composeErrors[8] = "(Utilizando diccionario %s)";

?>
