<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/cat/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings[0] = "Editar";
$ecStrings[1] = "Inserir";
$ecStrings[2] = " Contacte";
$ecStrings[3] = "Nom";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL";
$ecStrings[6] = "Grup";
$ecStrings[7] = "Comentaris";
$ecStrings[8] = "Tel&egrave;fon de casa";
$ecStrings[9] = "Tel&egrave;fon de la feina";
$ecStrings[10] = "Tel&egrave;fon m&ograve;bil";
$ecStrings[11] = "Adre&ccedil;a";
$ecStrings[12] = "Email alternatiu";
$ecStrings[13] = "Eliminar";
$ecStrings[14] = "Un altre";


$errors[0] = "No s'ha pogut inserir el contacte: Error en la base de dades.";
$errors[1] = "Ja existeix un contacte amb aquesta adre&ccedil;a.";
$errors[2] = "Click ";
$errors[3] = "aquí";
$errors[4] = " per editar aquest registre.";
$errors[5] = "No s'ha trobat el contacte, o s'ha denegat l'acc&eacute;s";
$errors[6] = "Est&agrave;s segur/-ra que vols eliminar el registre de \"";
$errors[7] = "\"?";

?>
