<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/no/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Tor Olsen <tor@monet.no>
********************************************************/

$cStrings[0] = "Kontakter";
$cStrings[1] = "Legg til kontakt";
$cStrings[2] = " Kontakt";
$cStrings[3] = "Navn";
$cStrings[4] = "E-post";
$cStrings[5] = "URL";
$cStrings[6] = "Gruppe";
$cStrings[7] = "Kommentar";
$cStrings[8] = "Legg til/Rediger kontakt";
$cStrings[9] = "E-post";
$cStrings[10] = "Skriv";


$cStrings["close"] = "Lukk vindu";
$cStrings["addto"] = "Legg til kontakt i %s";
$cStrings["showgrp"] = "Vis %s";
$cStrings["all"] = "Alle";
$cStrings["instructions"] = "Klikk på navnet for å legge til.  Du kan også klikke på gruppenavn for att legga til alle i den gruppen.";
$cStrings["share"] = "Gjør kontakten offentlig";
$cStrings["add_contact"] = "Legg til kontakt";
$cStrings["edit_contact"] = "Rediger kontakt";
$cStrings["add"] = "Legg til";
$cStrings["edit"] = "Oppdater";
$cStrings["export"] = "Eksporter";
$cStrings["import"] = "Importer";
$cStrings["exportall"] = "Eksporter alle kontakter";
$cStrings["exportgroups"] = "Eksporter grupper";
$cStrings["exportentries"] = "Eksporter kontakter";
$cStrings["format"] = "Format";
$cStrings["filename"] = "Filnavn";

$cErrors[0] = "Kontaktlisten er tom";
$cErrors[1] = "Kunne inte lese kontaktposten.";


?>