<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "新建日程安排";
$calStr["edit_schedule"] = "编辑日程安排";
$calStr["weekof"] = "本周(当前日期: %d)";
$calStr["title"] = "主题:";
$calStr["color"] = "颜色:";
$calStr["colors"] = array("#990000"=>"深红", "#FF0000"=>"红色", "#000099"=>"深蓝", "#0000FF"=>"蓝色", 
					"#006600"=>"深绿", "#00FF00"=>"绿色", "#9900FF"=>"紫色", "#00FFFF"=>"青色",
					"#FF6600"=>"橙色", "#FFFF00"=>"黄色", "#FF00FF"=>"粉色", ""=>"自动");
$calStr["starts"] = "开始日期:";
$calStr["ends"] = "结束日期:";
$calStr["from"] = "开始时间:";
$calStr["until"] = "结束时间:";
$calStr["repeat_on"] = "重复";
$calStr["of"] = "每";
$calStr["weeks"] = array(1=>"第一周", 2=>"第二周", 3=>"第三周", 4=>"第四周"); 
$calStr["week_blurb"] = "上面为每个月中的指定周 (直到结束日期)。<br>如果不选，则每周重复。";
$calStr["monthly"] = "每月重复";
$calStr["yearly"] = "每年重复";
$calStr["place"] = "地点:";
$calStr["description"] = "说明:";
$calStr["add"] = "新建";
$calStr["update"] = "更新";
$calStr["Delete"] = "删除";
?>
