<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/tw/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings["folders"] = "文件夹";
$toolStrings["inbox"] = "收件箱";
$toolStrings["compose"] = "写信";
$toolStrings["contacts"] = "地址簿";
$toolStrings["search"] = "查找";
$toolStrings["prefs"] = "选项";
$toolStrings["logout"] = "退出";
$toolStrings["go"] = "go";

$toolStrings["calendar"] = "日历";
$toolStrings["bookmarks"] = "收藏夹";


?>
