<?php
/********************************************************
	lang/eng/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Stefan Pettersson <stefan@pezzen.org>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/contacts.inc");

$cStrings[0] = "Kontakter";
$cStrings[1] = "Lägg till kontakt";
$cStrings[2] = " Kontakt";
$cStrings[3] = "Namn";
$cStrings[4] = "Email";
$cStrings[5] = "URI";
$cStrings[6] = "Grupp";
$cStrings[7] = "Kommentar";
$cStrings[8] = "Lägg till/redigera Kontakt";
$cStrings[9] = "Email";
$cStrings[10] = "Maila";

$cStrings["close"] = "Stäng fönster";
$cStrings["addto"] = "LÄgg till kontakt i %s";
$cStrings["showgrp"] = "VIsa %s";
$cStrings["all"] = "Alla";
$cStrings["instructions"] = "Klicka på namnen för att lägga till.  Du kan också klicka på gruppnamn för att lägga till alla i den gruppen.";
$cStrings["share"] = "Gör kontakten publik";
$cStrings["add_contact"] = "Lägg till kontakt";
$cStrings["edit_contact"] = "Redigera kontakt";
$cStrings["add"] = "Lägg till";
$cStrings["edit"] = "Uppdatera";
$cStrings["export"] = "Exportera";
$cStrings["import"] = "Importera";
$cStrings["exportall"] = "Exportera alla kontakter";
$cStrings["exportgroups"] = "Exportera grupper";
$cStrings["exportentries"] = "Exportera kontakter";
$cStrings["format"] = "Format";
$cStrings["filename"] = "Filnamn";

$cErrors[0] = "Kontaktlistan är tom";
$cErrors[1] = "Kunde inte läsa kontaktposten.";


?>
