<?php 
/********************************************************
	lang/<lang>/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Stefan Pettersson <stefan@pezzen.org>

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="Användarnamn";
$loginStrings[1]="Lösenord";
$loginStrings[2]="Server";
$loginStrings[3]="Protokoll";
$loginStrings[4]="Rootsökväg";
$loginStrings[5]="Språk";
$loginStrings[6]="Logga in";

$loginErrors[0]="Unauthorized host";
$loginErrors[1]="Error: Sökvägen till \"uploads\" hittades inte";
$loginErrors[2]="Error: Sökvägen till\"users\" hittades inte";
$loginErrors[3]="Error: Sökvägen till\"sessions\" hittades inte";

?>