<?php
/********************************************************
	lang/eng/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/bookmarks.inc");

$bmStrings['pubtitle'] = '%name\'s Bookmarks';
$bmStrings["bookmarks"] = "Bookmarks";
$bmStrings["identities"] = "Identities";
$bmStrings["edit"] = "Update";
$bmStrings["name"] = "Name";
$bmStrings["url"] = "URL";
$bmStrings["rss"] = "RSS/RDF";
$bmStrings["category"] = "Category";
$bmStrings["other"] = "Specify-&gt;";
$bmStrings["comments"] = "Comments";
$bmStrings["add"] = "Add";
$bmStrings["new"] = "New Entry";
$bmStrings["edit_url"] = "Edit Entry";
$bmStrings["delete"] = "Delete";
$bmStrings['refresh'] = 'Refresh';
$bmStrings['private'] = 'Make entry private';
$bmStrings['public url'] = 'Public URL: %url';
$bmStrings['pubtitlenews'] = '%name\'s RSS Feeds';
$bmStrings['rss feeds'] = 'RSS Feeds';

$bmError[1] = "Name or URL required";
$bmError[2] = "This feature has been disabled.";
?>