<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Add Schedule";
$calStr["edit_schedule"] = "Edit Schedule";
$calStr["weekof"] = "Week of: %d";
$calStr["title"] = "Title:";
$calStr["color"] = "Color:";

//for $calStr['color_names'], translate strings
//on the right hand side of equal sign
$calStr["color_names"]['Dark Red'] = 'Dark Red';
$calStr["color_names"]['Red'] = 'Red';
$calStr["color_names"]['Deep Blue'] = 'Deep Blue';
$calStr["color_names"]['Blue'] = 'Blue';
$calStr["color_names"]['Dark Green'] = 'Dark Green';
$calStr["color_names"]['Green'] = 'Green';
$calStr["color_names"]['Purple'] = 'Purple';
$calStr["color_names"]['Cyan'] = 'Cyan';
$calStr["color_names"]['Orange'] = 'Orange';
$calStr["color_names"]['Yellow'] = 'Yellow';
$calStr["color_names"]['Magenta'] = 'Magenta';
$calStr["color_names"]['No Color'] = 'No Color';

$calStr["starts"] = "Starts on:";
$calStr["ends"] = "Ends on:";
$calStr["from"] = "from:";
$calStr["until"] = "until:";
$calStr["repeat_on"] = "Repeat on";
$calStr["of"] = "of every";
$calStr["weeks"] = array(1=>"first week", 2=>"second week", 3=>"third week", 4=>"fourth week"); 
$calStr["week_blurb"] = "...of every month (until end date).<br>Will repeat on all weeks if none are selected.";
$calStr["monthly"] = "Repeat monthly";
$calStr["yearly"] = "Repeat annually";
$calStr["place"] = "Place:";
$calStr["description"] = "Description:";
$calStr["add"] = "Add";
$calStr["update"] = "Update";
$calStr["Delete"] = "Delete";
$calStr["go"] = "Go";
$calStr["disabled"] = "The calendar feature is disabled.";
$calStr["public"] = "Share entry";
$calStr["publish"] = "Make entry public";
$calStr['name'] = '%name\'s Schedule';
$calStr['public url'] = 'Public URL: %url';
$calStr['no schedules'] = '<p>No schedules have been entered for this week.  <br>Click on the dates above to enter new schedules.';
$calStr['no schedules public'] = '<p>No schedules have been entered for this week.';
$calStr['all day'] = "All Day";
$calStr['is all day'] = 'This is an all-day event';
$calStr['format'] = 'Format:';
$calStr['boxed'] = 'Boxed';
$calStr['list'] = 'List';
$calStr['scale'] = 'Scale:';
$calStr['bigger'] = 'Bigger';
$calStr['smaller'] = 'Smaller';
?>