<?php
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/read_message.inc");


$rmStrings[0] = "Index";
$rmStrings[1] = "Reply";
$rmStrings[2] = "Forward";
$rmStrings[3] = "Undelete";
$rmStrings[4] = "Delete";
$rmStrings[5] = "Move";
$rmStrings[6] = "Parts";
$rmStrings[7] = "This is an HTML message. ";
$rmStrings[8] = "Click here to read it.";
$rmStrings[9] = "Source";
$rmStrings[10] = "Size";
$rmStrings[11] = "Unread";
$rmStrings[12] = "Header";
$rmStrings[13] = "Report Spam";
$rmStrings[14] = "Re. To All";
$rmStrings[15] = "Replied";
$rmStrings[16] = "Printable";
$rmStrings[17] = 'This message is encoded with a character different to your preferred character set.  If you have trouble viewing the message below, <a href="%url">click here</a>';
$rmStrings[18] = 'This message is encoded with a unsupported character set.  If you have trouble viewing the message, try an alternative character set: %menu';
$rmStrings[19] = "View";
$rmStrings[20] = 'Read';
$rmStrings[21] = 'Show';
$rmStrings[22] = 'Action';
$rmStrings[23] = 'Message %message in thread';
$rmStrings[24] = 'Move thread';
$rmStrings[25] = 'HTML code with potentially malicious uses were found and removed from the message.<br>';
$rmStrings[25].= 'If this message is from a trusted source, <a href="%url">click here</a> to view the message unaltered.';

$rmStrings['back'] = 'Back';
$rmStrings['next'] = 'Next';
$rmStrings['previous'] = 'Previous';
$rmStrings['newer'] = 'Newer';
$rmStrings['older'] = 'Older';
?>