<?php
/********************************************************
	lang/de/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Neue Wiederholung";
$calStr["edit_schedule"] = "Wiederholung &auml;ndern";
$calStr["weekof"] = "Woche vom: %d";
$calStr["title"] = "Titel:";
$calStr["color"] = "Farbe:";
$calStr["colors"] = array (
  '#990000' => 'dunkelrot',
  '#FF0000' => 'rot',
  '#000099' => 'dunkelblau',
  '#0000FF' => 'blau',
  '#006600' => 'dunkelgrün',
  '#00FF00' => 'gr&uuml;n',
  '#9900FF' => 'lila',
  '#00FFFF' => 'cyan',
  '#FF6600' => 'orange',
  '#FFFF00' => 'gelb',
  '#FF00FF' => 'magenta',
);
$calStr["color_names"] = array (
  'Dark Red' => 'Dunkelrot',
  'Red' => 'Rot',
  'Deep Blue' => 'Dunkelblau',
  'Blue' => 'Blau',
  'Dark Green' => 'Dunkelgr&uuml;n',
  'Green' => 'Gr&uuml;n',
  'Purple' => 'Lila',
  'Cyan' => 'Cyan',
  'Orange' => 'Orange',
  'Yellow' => 'Gelb',
  'Magenta' => 'Magenta',
  'No Color' => 'keine Farbe',
);
$calStr["starts"] = "Beginnt am:";
$calStr["ends"] = "Endet am:";
$calStr["from"] = "von:";
$calStr["until"] = "bis:";
$calStr["repeat_on"] = "Wiederholen am";
$calStr["of"] = "jeder";
$calStr["weeks"] = array (
  1 => 'ersten Woche', 
  2 => 'zweiten Woche', 
  3 => 'dritten Woche', 
  4 => 'vierten Woche',
);
$calStr["week_blurb"] = "... des Monats (bis zum Enddatum).<br>Ohne Auswahl wird jede Woche wiederholt.";
$calStr["monthly"] = "Monatliche Wiederholung";
$calStr["yearly"] = "J&auml;hrliche Wiederholung";
$calStr["place"] = "Ort:";
$calStr["description"] = "Beschreibung:";
$calStr["add"] = "Speichern";
$calStr["update"] = "Speichern";
$calStr["Delete"] = "L&ouml;schen";
$calStr["go"] = "Ok";
$calStr["disabled"] = "Die Kalender-Funktion ist nicht verf&uuml;gbar.";
$calStr["public"] = "Eintrag &ouml;ffentlich machen";
$calStr["no schedules"] = "<p>Es gibt noch keine Eintr&auml;ge für diese Woche  <br>Klicke oben auf ein Datum um einen Eintrag einzugeben.";
$calStr["all day"] = "Ganztag";
$calStr["is all day"] = "Dies ist ein ganzt&auml;giges Ereignis";

?>
