 <?php
/********************************************************
	lang/de/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/contacts.inc");

$cStrings[0] = "Kontakte";
$cStrings[1] = "Neuer Kontakt";
$cStrings[2] = " Kontakt";
$cStrings[3] = "Name";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Gruppe";
$cStrings[7] = "Kommentar";
$cStrings[8] = "Kontakt speichern";
$cStrings[9] = "Email";
$cStrings[10] = "Neue Nachricht";
$cStrings["close"] = "Fenster schlie&szlig;en";
$cStrings["addto"] = "Kontakt in Feld &uuml;bernehmen: %s";
$cStrings["showgrp"] = "Zeige Gruppe %s";
$cStrings["all"] = "Alle";
$cStrings["instructions"] = "Klick auf Namen &uuml;bernimmt die Adresse.<br>Klick auf Gruppennamen &uuml;bernimmt alle Adressen einer Gruppe.";
$cStrings["share"] = "Eintrag &ouml;ffentlich machen";
$cStrings["add_contact"] = "Neuer Kontakt";
$cStrings["edit_contact"] = "Kontakt editieren";
$cStrings["add"] = "Speichern";
$cStrings["edit"] = "Bearbeiten";
$cStrings["export"] = "Export";
$cStrings["import"] = "Import";
$cStrings["exportall"] = "Exportiere alle Eintr&auml;ge";
$cStrings["exportgroups"] = "Exportiere Gruppen";
$cStrings["exportentries"] = "Exportiere gew&auml;hlte Eintr&auml;ge";
$cStrings["format"] = "Format";
$cStrings["filename"] = "Dateiname";
$cErrors[0] = "Keine Kontakte vorhanden.";
$cErrors[1] = "Kann auf angegebenen Eintrag nicht zugreifen";
?>
