<?php
/********************************************************
	lang/de/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_folders.inc");

$efStrings[0] = "Ordnerverwaltung";
$efStrings[1] = "Neuer Ordner";
$efStrings[2] = "Neuer Ordner: ";
$efStrings[3] = "Erstellen";
$efStrings[4] = "Ordner l&ouml;schen";
$efStrings[5] = "L&ouml;schen";
$efStrings[6] = "Ordner umbenennen";
$efStrings[7] = "Umbenennen";
$efStrings[8] = "Gew&auml;hlte Ordner";
$efStrings[9] = "Ausw&auml;hlen";
$efStrings[10] = "Nicht gew&auml;hlte Ordner";
$efStrings[11] = "Nicht mehr ausw&auml;hlen";
$errors[0] = "Neuer Ordner: ";
$errors[1] = "Konnte neuen Ordner nicht anlegen: ";
$errors[2] = "Ordner gel&ouml;scht: ";
$errors[3] = "Konnte Ordner nicht l&ouml;schen: ";
$errors[4] = "Ordner umbenannt: ";
$errors[5] = "Konnte Ordner nicht umbenennen: ";
$errors[6] = "Ordner werden nur für IMAP-Zug&auml;nge unterstützt.";

?>
