<?php
/********************************************************
	lang/de/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0] = "Benutzer";
$loginStrings[1] = "Passwort";
$loginStrings[2] = "Server";
$loginStrings[3] = "Protokoll";
$loginStrings[4] = "Wurzelverzeichnis";
$loginStrings[5] = "Sprache";
$loginStrings[6] = "Login";

$loginErrors[0] = "Nicht authorisierter Host";
$loginErrors[1] = "Fehler: &quot;uploads&quot; Verzeichnis nicht gefunden!";
$loginErrors[2] = "Fehler: &quot;users&quot; Benutzerverzeichnis nicht gefunden!";
$loginErrors[3] = "Fehler: &quot;sessions&quot; Session-Verzeichnis nicht gefunden!";

?>
