<?php
/********************************************************
	lang/de/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/read_message.inc");

$rmStrings[0] = "Zur&uuml;ck";
$rmStrings[1] = "Antworten";
$rmStrings[2] = "Weiterleiten";
$rmStrings[3] = "Gel&ouml;schte wiederherstellen";
$rmStrings[4] = "L&ouml;schen";
$rmStrings[5] = "Verschieben";
$rmStrings[6] = "Teile";
$rmStrings[7] = "Dies ist eine HTML-Nachricht. ";
$rmStrings[8] = "Klicken Sie hier, um sie zu lesen.";
$rmStrings[9] = "Quelle";
$rmStrings[10] = "Gr&ouml;&szlig;e";
$rmStrings[11] = "Als ungelesen markieren";
$rmStrings[12] = "Mail-Header anzeigen";
$rmStrings[13] = "Spam-Beschwerde";
$rmStrings[14] = "Antwort an alle";
$rmStrings[15] = "Sie haben auf diese Nachricht geantwortet";
$rmStrings[16] = "Druckansicht";
$rmStrings[17] = "Diese Nachricht ist nicht mit Ihrem Standard-Character-Set kodiert.  Wenn die Nachricht nicht korrekt angezeigt wird, <a href=\"%url\">hier klicken</a>.";
$rmStrings[18] = "Diese Nachricht ist mit einem nicht unterstützten Character-Set kodiert.  Wenn die Nachricht nicht korrekt angezeigt wird, bitte einen anderen Character-Set w&auml;hlen: %menu";
$rmStrings[19] = "View";
$rmStrings[20] = "Read";
$rmStrings[21] = "Anzeigen";
$rmStrings[22] = "Aktion";

$rmStrings['back'] = 'Zur&uuml;ck';
$rmStrings['next'] = 'Weiter';
$rmStrings['previous'] = 'Vorige';
$rmStrings['newer'] = '&Auml;lter';
$rmStrings['older'] = 'Neuer';

?>
